package com.btpn.migration.los.constant;

import java.util.HashMap;
import java.util.Map;

public class DataMapping {

	// Cara ambil dari excel
	// Cari sumbernya dari Data.Validity dapat Dati_3
	// Ketik names define Dati_3 akan mengarah ke Sheet Dati_3
	// Lalu pilih Data Consilidate akan muncul copy to $Value.$AX1
	// Buat sheet baru lalu copy $Value.$AX1 copy aja ke bawah
	
	private Map<String, String> dati2Map = new HashMap<String, String>();
	
	private static DataMapping dataMapping = null;
	
	private DataMapping() {		
		//Mapping Dari Dati2 yang ada di excel (InformasiDebitur.H121) ke  CommonService TypeCity
		dati2Map.put("Bekasi, Kab. - 0102", "KAB. BEKASI");
		dati2Map.put("Ambon, Kota. - 8191", "KOTA AMBON");
		dati2Map.put("Badung, Kab. - 7204", "KAB. BANDUNG");
		dati2Map.put("Balikpapan, Kota. - 5492", "KOTA BALIKPAPAN");
		dati2Map.put("Bandar Lampung, Kota. - 3991", "KOTA BANDAR LAMPUNG");
		dati2Map.put("Bandung Barat, Kab - 0122", "KAB. BANDUNG BARAT");
		dati2Map.put("Bandung, Kab. - 0111", "KAB. BANDUNG");
		dati2Map.put("Bandung, Kota. - 0191", "KOTA BANDUNG");
		dati2Map.put("Bandung, Kota. - 0192", "KOTA BANDUNG");
		dati2Map.put("Banggai Kepulauan, Kab - 6005", "KAB. BANGGAI KEPULAUAN");
		dati2Map.put("Bangka Belitung, Kab - 3707", "");
		dati2Map.put("Banjar, Kab. - 5101", "KAB. BANJAR");
		dati2Map.put("Banjarbaru, Kota. - 5192", "KOTA BANJARBARU");
		dati2Map.put("Banjarmasin, Kota. - 5191", "KOTA BANJARMASIN");
		dati2Map.put("Bantul, Kab. - 0501", "KAB. BANTUL");
		dati2Map.put("Banyumas, Kab. - 0914", "KAB. BANYUMAS");
		dati2Map.put("Banyuwangi, Kab. - 1211", "KAB. BANYUWANGI");
		dati2Map.put("Batam, Kota - 3892", "KOTA BATAM");
		dati2Map.put("Batang, Kab. - 0929", "KAB. BATANG");
		dati2Map.put("Batanghari, Kab. - 3101", "KAB. BATANGHARI");
		dati2Map.put("Batu, Kota. - 1271", "KOTA BATU");
		dati2Map.put("Bekasi, Kota. - 0198", "KOTA BEKASI");
		dati2Map.put("Belu, Kab. - 7404", "KAB. BELU");
		dati2Map.put("Bengkalis, Kab. - 3502", "KAB. BENGKALIS");
		dati2Map.put("Binjai, Kota. - 3392", "KOTA BINJAI");
		dati2Map.put("Binjai, Kota. - 3393", "KOTA BINJAI");
		dati2Map.put("Blora, Kab. - 0913", "KAB. BLORA");
		dati2Map.put("Bogor, Kab. - 0108", "KAB. BOGOR");
		dati2Map.put("Bogor, Kota. - 0192", "KOTA BOGOR");
		dati2Map.put("Bogor, Kota. - 0193", "KOTA BOGOR");
		dati2Map.put("Bogor, Kota. - 0194", "KOTA BOGOR");
		dati2Map.put("Bombana, Kab. - 6908", "KAB. BOMBANA");
		dati2Map.put("Bulukumba, Kab. - 6111", "KAB. BULUKUMBA");
		dati2Map.put("Cilacap, Kab. - 0915", "KAB. CILACAP");
		dati2Map.put("Cilegon, Kota. - 0291", "KOTA CILEGON");
		dati2Map.put("Cimahi, Kota. - 0196", "KOTA CIMAHI");
		dati2Map.put("Cirebon, Kab. - 0116", "KAB. CIREBON");
		dati2Map.put("Cirebon, Kota. - 0194", "KOTA CIREBON");
		dati2Map.put("Deli Serdang, Kab. - 3301", "KAB. DELI SERDANG");
		dati2Map.put("Demak, Kab. - 0903", "KAB. DEMAK");
		dati2Map.put("Denpasar, Kota. - 7291", "KOTA DENPASAR");
		dati2Map.put("Depok, Kota. - 0197", "KOTA DEPOK");
		dati2Map.put("Gianyar, Kab. - 7205", "KAB. GIANYAR");
		dati2Map.put("Gorontalo, Kota. - 6391", "KOTA GORONTALO");
		dati2Map.put("Gowa, Kab. - 6102", "KAB. GOWA");
		dati2Map.put("Gresik, Kab. - 1201", "KAB. GRESIK");
		dati2Map.put("Grobogan, Kab. - 0904", "KAB. GROBOGAN");
		dati2Map.put("Jakarta Barat, Wil. Kota - 0393", "KOTA ADM. JAKARTA BARAT");
		dati2Map.put("Jakarta Barat, Wil. Kota - 0394", "KOTA ADM. JAKARTA BARAT");
		dati2Map.put("Jakarta Barat, Wil. Kota - 0395", "KOTA ADM. JAKARTA BARAT");
		dati2Map.put("Jakarta Pusat, Wil. Kota - 0391", "KOTA ADM. JAKARTA PUSAT");
		dati2Map.put("Jakarta Pusat, Wil. Kota - 0392", "KOTA ADM. JAKARTA PUSAT");
		dati2Map.put("Jakarta Pusat, Wil. Kota - 0393", "KOTA ADM. JAKARTA PUSAT");
		dati2Map.put("Jakarta Selatan, Wil. Kota - 0394", "KOTA ADM. JAKARTA SELATAN");
		dati2Map.put("Jakarta Timur, Wil. Kota - 0395", "KOTA ADM. JAKARTA TIMUR");
		dati2Map.put("Jakarta Timur, Wil. Kota - 0396", "KOTA ADM. JAKARTA TIMUR");
		dati2Map.put("Jakarta Utara ., Wil. Kota - 0392", "KOTA ADM. JAKARTA UTARA");
		dati2Map.put("Jambi, Kota. - 3191", "KOTA JAMBI");
		dati2Map.put("Jember, Kab. - 1212", "KAB. JEMBER");
		dati2Map.put("Jembrana, Kab. - 7202", "KAB. JEMBRANA");
		dati2Map.put("Jepara, Kab. - 0911", "KAB. JEPARA");
		dati2Map.put("Kampar, Kab. - 3501", "KAB. KAMPAR");
		dati2Map.put("Karanganyar, Kab. - 0927", "KAB. KARANGANYAR");
		dati2Map.put("Karawang, Kab. - 0106", "KAB. KARAWANG");
		dati2Map.put("Kediri, Kota. - 1297", "KOTA KEDIRI");
		dati2Map.put("Kendal, Kab. - 0902", "KAB. KENDAL");
		dati2Map.put("Kendari, Kota. - 6991", "KOTA KENDARI");
		dati2Map.put("Ketapang, Kab. - 5303", "KAB. KETAPANG");
		dati2Map.put("Konawe, Kab. - 6906", "KAB. KONAWE");
		dati2Map.put("Kota Tangerang Selatan - 0294", "KOTA TANGERANG SELATAN");
		dati2Map.put("Kotawaringin Timur, Kab. - 5803", "KAB. KOTAWARINGIN TIMUR");
		dati2Map.put("Kubu Raya, Kab. - 5312", "KAB. KUBU RAYA");
		dati2Map.put("Kudus, Kab. - 0909", "KAB. KUDUS");
		dati2Map.put("Kuningan, Kab. - 0117", "KAB. KUNINGAN");
		dati2Map.put("Kupang, Kota. - 7491", "KOTA KUPANG");
		dati2Map.put("Labuhan Batu, Kab. - 3305", "KAB. LABUHANBATU");
		dati2Map.put("Lampung Selatan, Kab. - 3901", "KAB. LAMPUNG SELATAN");
		dati2Map.put("Lampung Timur, Kab. - 3907", "KAB. LAMPUNG TIMUR");
		dati2Map.put("Lampung Utara, Kab. - 3903", "KAB. LAMPUNG UTARA");
		dati2Map.put("Langkat, Kab. - 3302", "KAB. LANGKAT");
		dati2Map.put("Lombok Tengah, Kab. - 7102", "KAB. LOMBOK TENGAH");
		dati2Map.put("Luwu, Kab. - 6109", "KAB. LUWU");
		dati2Map.put("Madiun, Kab. - 1222", "KAB. MADIUN");
		dati2Map.put("Madiun, Kota. - 1298", "KOTA MADIUN");
		dati2Map.put("Magelang, Kab. - 0918", "KAB. MAGELANG");
		dati2Map.put("Magelang, Kota. - 0995", "KOTA MAGELANG");
		dati2Map.put("Majalengka, Kab. - 0119", "KAB. MAJALENGKA");
		dati2Map.put("Makassar, Kota. - 6191", "KOTA MAKASSAR");
		dati2Map.put("Malang, Kab. - 1213", "KAB. MALANG");
		dati2Map.put("Malang, Kota. - 1293", "KOTA MALANG");
		dati2Map.put("Malang, Kota. - 1294", "KOTA MALANG");
		dati2Map.put("Malinau, Kab. - 5410", "KAB. MALINAU");
		dati2Map.put("Maros, Kab. - 6107", "KAB. MAROS");
		dati2Map.put("Mataram, Kota. - 7191", "KOTA MATARAM");
		dati2Map.put("Medan, Kota. - 3396", "KOTA MEDAN");
		dati2Map.put("Medan, Kota. - 3397", "KOTA MEDAN");
		dati2Map.put("Menado, Kota. - 6291", "KOTA MANADO");
		dati2Map.put("Metro, Kota. - 3992", "KOTA METRO");
		dati2Map.put("Minahasa, Kab. - 6202", "KAB. MINAHASA");
		dati2Map.put("Mojokerto, Kab. - 1203", "KAB. MOJOKERTO");
		dati2Map.put("Mojokerto, Kota. - 1292", "KOTA MOJOKERTO");
		dati2Map.put("Padang, Kota. - 3492", "KOTA PADANG");
		dati2Map.put("Palembang, Kota. - 3691", "KOTA PALEMBANG");
		dati2Map.put("Palu, Kota. - 6091", "KOTA PALU");
		dati2Map.put("Pangkajene Kepulauan, Kab. - 6118", "KAB. PANGKAJENE KEPULAUAN");
		dati2Map.put("Pasuruan, Kab. - 1214", "KAB. PASURUAN");
		dati2Map.put("Pati, Kab. - 0908", "KAB. PATI");
		dati2Map.put("Pekanbaru, Kota. - 3591", "KOTA PEKANBARU");
		dati2Map.put("Pelalawan, Kab. - 3510", "KAB. PELALAWAN");
		dati2Map.put("Pemalang, Kab. - 0910", "KAB. PEMALANG");
		dati2Map.put("Pematang Siantar, Kota. - 3393", "KOTA PEMATANG SIANTAR");
		dati2Map.put("Ponorogo, Kab. - 1225", "KAB. PONOROGO");
		dati2Map.put("Pontianak, Kab. - 5301", "");
		dati2Map.put("Pontianak, Kota. - 5391", "KOTA PONTIANAK");
		dati2Map.put("Pontianak, Kota. - 5392", "KOTA PONTIANAK");
		dati2Map.put("Pringsewu, Kab - 3910", "KAB. PRINGSEWU");
		dati2Map.put("Probolinggo, Kota. - 1295", "KOTA PROBOLINGGO");
		dati2Map.put("Purbalingga, Kab. - 0916", "KAB. PURBALINGGA");
		dati2Map.put("Purworejo, Kab. - 0921", "KAB. PURWOREJO");
		dati2Map.put("Rembang, Kab. - 0912", "KAB. REMBANG");
		dati2Map.put("Salatiga, Kota. - 0992", "KOTA SALATIGA");
		dati2Map.put("Samarinda, Kota. - 5491", "KOTA SAMARINDA");
		dati2Map.put("Samarinda, Kota. - 5492", "KOTA SAMARINDA");
		dati2Map.put("Sambas, Kab. - 5302", "KAB. SAMBAS");
		dati2Map.put("Selayar, Kab. - 6114", "KAB. KEPULAUAN SELAYAR");
		dati2Map.put("Semarang, Kab. - 0901", "KAB. SEMARANG");
		dati2Map.put("Semarang, Kota. - 0991", "KOTA SEMARANG");
		dati2Map.put("Semarang, Kota. - 0992", "KOTA SEMARANG");
		dati2Map.put("Serang, Kab. - 0203", "KAB. SERANG");
		dati2Map.put("Serang. Kota. - 0293", "KOTA SERANG");
		dati2Map.put("Serdang Bedagai, Kab - 3319", "KAB. SERDANG BEDAGAI");
		dati2Map.put("Siak, Kab. - 3511", "KAB. SIAK");
		dati2Map.put("Sidoarjo, Kab. - 1202", "KAB. SIDOARJO");
		dati2Map.put("Singkawang, Kota. - 5392", "KOTA SINGKAWANG");
		dati2Map.put("Sleman, Kab. - 0502", "KAB. SLEMAN");
		dati2Map.put("Subang, Kab. - 0121", "KAB. SUBANG");
		dati2Map.put("Sukoharjo, Kab. - 0926", "KAB. SUKOHARJO");
		dati2Map.put("Sumbawa, Kab. - 7104", "KAB. SUMBAWA");
		dati2Map.put("Surabaya, Kota. - 1291", "KOTA SURABAYA");
		dati2Map.put("Surabaya, Kota. - 1292", "KOTA SURABAYA");
		dati2Map.put("Surakarta, Kota. - 0996", "KOTA SURAKARTA");
		dati2Map.put("Tabalong, Kab. - 5109", "KAB. TABALONG");
		dati2Map.put("Tabanan, Kab. - 7203", "KAB. TABANAN");
		dati2Map.put("Takalar, Kab. - 6115", "KAB. TAKALAR");
		dati2Map.put("Tangerang, Kab. - 0204", "KAB. TANGERANG");
		dati2Map.put("Tangerang, Kota. - 0292", "KOTA TANGERANG");
		dati2Map.put("Tangerang, Kota. - 0293", "KOTA TANGERANG");
		dati2Map.put("Tangerang, Kota. - 0294", "KOTA TANGERANG");
		dati2Map.put("Tanjungpinang, Kota - 3891", "KOTA TANJUNG PINANG");
		dati2Map.put("Tarakan, Kota. - 5493", "KOTA TARAKAN");
		dati2Map.put("Tasikmalaya, Kota. - 0195", "KOTA TASIKMALAYA");
		dati2Map.put("Tasikmalaya, Kota. - 0196", "KOTA TASIKMALAYA");
		dati2Map.put("Tasikmalaya, Kota. - 0197", "KOTA TASIKMALAYA");
		dati2Map.put("Tegal, Kab. - 0906", "KAB. TEGAL");
		dati2Map.put("Tegal, Kota. - 0994", "KOTA TEGAL");
		dati2Map.put("Temanggung, Kab. - 0919", "KAB. TEMANGGUNG");
		dati2Map.put("Tomohon, Kota - 6294", "KOTA TOMOHON");
		dati2Map.put("Tulang Bawang, Kab. - 3905", "KAB. TULANG BAWANG");
		dati2Map.put("Tulungagung, Kab. - 1219", "KAB. TULUNGAGUNG");
		dati2Map.put("Wonogiri, Kab. - 0928", "KAB. WONOGIRI");
		dati2Map.put("Yapen-Waropen, Kab. - 8210", "KAB. WAROPEN");
		dati2Map.put("Yogyakarta, Kota. - 0591", "KOTA YOGYAKARTA");
		
		// Unmapping
		dati2Map.put("Aceh Barat Daya, Kab. - 3213","");
		dati2Map.put("Aceh Barat, Kab. - 3206","");
		dati2Map.put("Besar, Kab. - 3201","");
		dati2Map.put("Aceh Jaya, Kab. - 3214","");
		dati2Map.put("Aceh Jeumpa/Bireuen, Kab. - 3210","");
		dati2Map.put("Aceh Selatan, Kab. - 3205","");
		dati2Map.put("Aceh Singkil, Kab. - 3209","");
		dati2Map.put("Aceh Tamiang, Kab. - 3211","");
		dati2Map.put("Aceh Tengah, Kab. - 3207","");
		dati2Map.put("Aceh Tenggara, Kab. - 3208","");
		dati2Map.put("Aceh Timur, Kab. - 3204","");
		dati2Map.put("Aceh Utara, Kab. - 3203","");
		dati2Map.put("Agam, Kab. - 3401","");
		dati2Map.put("Alor, Kab. - 7405","");
		dati2Map.put("Anambas, Kab - 3805","");
		dati2Map.put("Angkola Sipirok, Kab - 3320","");
		dati2Map.put("Asahan, Kab. - 3306","");
		dati2Map.put("Asmat, Kab. - 8228","");
		dati2Map.put("Balangan, Kab. - 5111", "");
		dati2Map.put("Banda Aceh, Kota. - 3291", "");
		dati2Map.put("Bangka Barat, Kab - 3703", "");
		dati2Map.put("Bangka Selatan, Kab - 3704", "");
		dati2Map.put("Bangka Tengah, Kab - 3705", "");
		dati2Map.put("Bangka, Kab. - 3701", "");
		dati2Map.put("Bangkalan, Kab. - 1208", "");
		dati2Map.put("Bangli, Kab. - 7207", "");
		dati2Map.put("Banjar, Kota. - 0180", "");
		dati2Map.put("Banjarnegara, Kab. - 0917", "");
		dati2Map.put("Bantaeng, Kab. - 6112", "");
		dati2Map.put("Banyuasin, Kab - 3613", "");
		dati2Map.put("Barito Kuala, Kab. - 5107", "");
		dati2Map.put("Barito Selatan, Kab. - 5806", "");
		dati2Map.put("Barito Timur, Kab. - 5805", "");
		dati2Map.put("Barito Utara, Kab. - 5808", "");
		dati2Map.put("Barru, Kab. - 6116", "");
		dati2Map.put("Batu Bara, Kab - 3321", "");
		dati2Map.put("Bau-Bau,Kota. - 6990", "");
		dati2Map.put("Belitung Timur, Kab - 3706", "");
		dati2Map.put("Belitung, Kab. - 3702", "");
		dati2Map.put("Bener Meriah, Kab - 3217", "");
		dati2Map.put("Bengkayang, Kab. - 5307", "");
		dati2Map.put("Bengkulu Selatan, Kab. - 2301", "");
		dati2Map.put("Bengkulu Tengah, Kab - 2309", "");
		dati2Map.put("Bengkulu Utara, Kab. - 2302", "");
		dati2Map.put("Bengkulu, Kota. - 2391", "");
		dati2Map.put("Berau, Kab. - 5402", "");
		dati2Map.put("Biak Numfor, Kab. - 8202", "");
		dati2Map.put("Bima, Kab. - 7105", "");
		dati2Map.put("Bintan, Kab (d/h Kab. Kepulauan Riau - 3804", "");
		dati2Map.put("Bitung, Kota. - 6293", "");
		dati2Map.put("Blitar, Kab. - 1221", "");
		dati2Map.put("Blitar, Kota. - 1296", "");
		dati2Map.put("Bojonegoro, Kab. - 1227", "");
		dati2Map.put("Bolaang Mongondow Selatan, Kab - 6212", "");
		dati2Map.put("Bolaang Mongondow Timur, Kab - 6213", "");
		dati2Map.put("Bolaang Mongondow, Kab. - 6203", "");
		dati2Map.put("Bolaang Mongoundow Utara, Kab. - 6210", "");
		dati2Map.put("Bondowoso, Kab. - 1209", "");
		dati2Map.put("Bone, Kab. - 6105", "");
		dati2Map.put("Bonebolango, Kab. - 6303", "");
		dati2Map.put("Bontang, Kota. - 5494", "");
		dati2Map.put("Boven Digoel, Kab. - 8226", "");
		dati2Map.put("Boyolali, Kab. - 0924", "");
		dati2Map.put("Brebes, Kab. - 0907", "");
		dati2Map.put("Bualemo, Kab. - 6302", "");
		dati2Map.put("Bukittinggi, Kota. - 3491", "");
		dati2Map.put("Buleleng, Kab. - 7201", "");
		dati2Map.put("Bulungan, Kab. - 5404", "");
		dati2Map.put("Bungo, Kab - 3112", "");
		dati2Map.put("Buol, Kab. - 6007", "");
		dati2Map.put("Buru Selatan, Kab - 8109", "");
		dati2Map.put("Buru, Kab - 8104", "");
		dati2Map.put("Buton Utara, Kab. - 6910", "");
		dati2Map.put("Buton, Kab. - 6901", "");
		dati2Map.put("Ciamis, Kab. - 0115", "");
		dati2Map.put("Cianjur, Kab. - 0110", "");
		dati2Map.put("Dairi, Kab. - 3307", "");
		dati2Map.put("Deiyai, Kab - 8240", "");
		dati2Map.put("Dharmasraya, Kab. - 3411", "");
		dati2Map.put("DI  LUAR  INDONESIA - 9999", "");
		dati2Map.put("Dogiyai, Kab. - 8233", "");
		dati2Map.put("Dompu, Kab. - 7106", "");
		dati2Map.put("Donggala, Kab. - 6001", "");
		dati2Map.put("Dumai, Kota. - 3592", "");
		dati2Map.put("Empat Lawang - 3617", "");
		dati2Map.put("Ende, Kab. - 7408", "");
		dati2Map.put("Enrekang, Kab. - 6121", "");
		dati2Map.put("Fak-Fak, Kab. - 8402", "");
		dati2Map.put("Flores Timur, Kab. - 7406", "");
		dati2Map.put("Garut, Kab. - 0114", "");
		dati2Map.put("Gayo Luwes, Kab. - 3212", "");
		dati2Map.put("Gorontalo Utara, Kab. - 6305", "");
		dati2Map.put("Gorontalo, Kab. - 6301", "");
		dati2Map.put("Gunung Kidul, Kab. - 0503", "");
		dati2Map.put("Gunung Mas, Kab. - 5807", "");
		dati2Map.put("Halmahera Barat, Kab. - 8305", "");
		dati2Map.put("Halmahera Selatan, Kab. - 8306", "");
		dati2Map.put("Halmahera Tengah, Kab. - 8302", "");
		dati2Map.put("Halmahera Timur, Kab. - 8304", "");
		dati2Map.put("Halmahera Utara, Kab. - 8303", "");
		dati2Map.put("Hulu Sungai Selatan, Kab. - 5104", "");
		dati2Map.put("Hulu Sungai Tengah, Kab. - 5105", "");
		dati2Map.put("Hulu Sungai Utara, Kab. - 5106", "");
		dati2Map.put("Humbang Hasundutan, Kab - 3316", "");
		dati2Map.put("Indragiri Hilir, Kab. - 3505", "");
		dati2Map.put("Indragiri Hulu, Kab. - 3504", "");
		dati2Map.put("Indramayu, Kab. - 0118", "");
		dati2Map.put("Intan Jaya, Kab - 8239", "");
		dati2Map.put("Jayapura, Kab. - 8201", "");
		dati2Map.put("Jayapura, Kota. - 8291", "");
		dati2Map.put("Jayawijaya, Kab. - 8213", "");
		dati2Map.put("Jeneponto, Kab. - 6113", "");
		dati2Map.put("Jombang, Kab. - 1204", "");
		dati2Map.put("Kaimana, Kab. - 8406", "");
		dati2Map.put("Kapuas Hulu, Kab. - 5306", "");
		dati2Map.put("Kapuas, Kab. - 5801", "");
		dati2Map.put("Karangasem, Kab. - 7208", "");
		dati2Map.put("Karimun, Kab - 3801", "");
		dati2Map.put("Karo, Kab. - 3303", "");
		dati2Map.put("Katingan, Kab. - 5811", "");
		dati2Map.put("Kaur, Kab - 2308", "");
		dati2Map.put("Kayong Utara, Kab. - 5311", "");
		dati2Map.put("Kebumen, Kab. - 0922", "");
		dati2Map.put("Kediri, Kab. - 1217", "");
		dati2Map.put("Keerom, Kab. - 8218", "");
		dati2Map.put("Kepahiang, Kab - 2305", "");
		dati2Map.put("Kepulauan Aru, Kota. - 8107", "");
		dati2Map.put("Kepulauan Mentawai, Kab. - 3409", "");
		dati2Map.put("Kepulauan Meranti, Kab - 3513", "");
		dati2Map.put("Kepulauan Seribu, Wilayah - 0396", "");
		dati2Map.put("Kepulauan Sitaro, Kab. - 6211", "");
		dati2Map.put("Kepulauan Sula, Kab. - 8307", "");
		dati2Map.put("kepulauan Talaud, Kab. - 6205", "");
		dati2Map.put("Kerinci, Kab. - 3105", "");
		dati2Map.put("Klaten, Kab. - 0923", "");
		dati2Map.put("Klungkung, Kab. - 7206", "");
		dati2Map.put("Kolaka Utara, Kab. - 6909", "");
		dati2Map.put("Kolaka, Kab. - 6904", "");
		dati2Map.put("Konawe Selatan, Kab. - 6907", "");
		dati2Map.put("Konawe Utara, Kab. - 6911", "");
		dati2Map.put("Kota Baru, Kab. - 5108", "");
		dati2Map.put("Kota Gunung Sitoli - 3397", "");
		dati2Map.put("Kota Sungai Penuh - 3192", "");
		dati2Map.put("Kota. Bima - 7192", "");
		dati2Map.put("Kota. Tomohon - 6294", "");
		dati2Map.put("Kotamobagu, Kota. - 6292", "");
		dati2Map.put("Kotawaringin Barat, Kab. - 5802", "");
		dati2Map.put("Kuantan Singingi, Kab. - 3512", "");
		dati2Map.put("Kulon Progo, Kab. - 0504", "");
		dati2Map.put("Kupang, Kab. - 7401", "");
		dati2Map.put("Kutai Barat, Kab. - 5405", "");
		dati2Map.put("Kutai Kartanegara, Kab. - 5401", "");
		dati2Map.put("Kutai Timur, Kab. - 5406", "");
		dati2Map.put("Labuanbatu Selatan, Kab - 3324", "");
		dati2Map.put("Labuanbatu Utara, Kab - 3325", "");
		dati2Map.put("Lahat, Kab. - 3609", "");
		dati2Map.put("Lamandau, Kab. - 5813", "");
		dati2Map.put("Lamongan, Kab. - 1229", "");
		dati2Map.put("Lampung Barat, Kab. - 3904", "");
		dati2Map.put("Lampung Tengah, Kab. - 3902", "");
		dati2Map.put("Landak, Kab. - 5308", "");
		dati2Map.put("Langsa, Kota. - 3294", "");
		dati2Map.put("Lanny Jaya, Kab. - 8234", "");
		dati2Map.put("Lebak, Kab. - 0201", "");
		dati2Map.put("Lebong, Kab - 2304", "");
		dati2Map.put("Lematang Ilir Ogan Tengah (Muara Enim), Kab. - 3608", "");
		dati2Map.put("Lembata, Kab. - 7413", "");
		dati2Map.put("Lhokseumawe, Kota. - 3293", "");
		dati2Map.put("Limapuluh Koto, Kab. - 3403", "");
		dati2Map.put("Lingga, Kab - 3802", "");
		dati2Map.put("Lombok Barat, Kab. - 7101", "");
		dati2Map.put("Lombok Timur, Kab. - 7103", "");
		dati2Map.put("Lombok Utara, Kab - 7108", "");
		dati2Map.put("Lubuklinggau, Kota. - 3693", "");
		dati2Map.put("Lumajang, Kab. - 1216", "");
		dati2Map.put("Luwu Timur, Kab (d/h Luwu Selatan) - 6122", "");
		dati2Map.put("Luwu Utara, Kab. - 6124", "");
		dati2Map.put("Magetan, Kab. - 1224", "");
		dati2Map.put("Majene, Kab. - 6402", "");
		dati2Map.put("Maluku Barat Daya, Kab - 8108", "");
		dati2Map.put("Maluku Tengah, Kab. - 8101", "");
		dati2Map.put("Maluku Tenggara Barat, Kab. - 8103", "");
		dati2Map.put("Maluku Tenggara, Kab. - 8102", "");
		dati2Map.put("Mamasa, Kab. - 6403", "");
		dati2Map.put("Mamberamo Raya, Kab. - 8232", "");
		dati2Map.put("Mamberamo Tengah, Kab. - 8235", "");
		dati2Map.put("Mamuju Utara, Kab. - 6404", "");
		dati2Map.put("Mamuju, Kota. - 6491", "");
		dati2Map.put("Mandailing Natal, Kab. - 3314", "");
		dati2Map.put("Manggarai Barat, Kab. - 7415", "");
		dati2Map.put("Manggarai Timur, Kab. - 7418", "");
		dati2Map.put("Manggarai, Kab. - 7410", "");
		dati2Map.put("Manokwari, Kab. - 8403", "");
		dati2Map.put("Mappi, Kab. - 8227", "");
		dati2Map.put("Maybrat, Kab - 8410", "");
		dati2Map.put("Melawi, Kab.. - 5310", "");
		dati2Map.put("Merangin, Kab. - 3111", "");
		dati2Map.put("Merauke, Kab. - 8211", "");
		dati2Map.put("Mesuji, Kab - 3912", "");
		dati2Map.put("Mimika, Kab. - 8215", "");
		dati2Map.put("Minahasa Selatan, Kab. - 6206", "");
		dati2Map.put("Minahasa Tenggara, Kab. - 6209", "");
		dati2Map.put("Minahasa Utara, Kab. - 6207", "");
		dati2Map.put("Morowali, Kab. - 6006", "");
		dati2Map.put("Muaro Jambi, Kab. - 3106", "");
		dati2Map.put("Mukomuko, Kab - 2306", "");
		dati2Map.put("Muna, Kab. - 6903", "");
		dati2Map.put("Murung Raya, Kab. - 5804", "");
		dati2Map.put("Musi Banyuasin, Kab. - 3606", "");
		dati2Map.put("Musi Rawas, Kab. - 3610", "");
		dati2Map.put("Nabire, Kab. - 8214", "");
		dati2Map.put("Nagan Raya, Kab. - 3215", "");
		dati2Map.put("Nagekeo, Kab. - 7419", "");
		dati2Map.put("Natuna, Kab - 3803", "");
		dati2Map.put("Nduga Tengah, Kab. - 8236", "");
		dati2Map.put("Ngada, Kab. - 7409", "");
		dati2Map.put("Nganjuk, Kab. - 1218", "");
		dati2Map.put("Ngawi, Kab. - 1223", "");
		dati2Map.put("Nias Barat, Kab - 3326", "");
		dati2Map.put("Nias Selatan, Kab - 3315", "");
		dati2Map.put("Nias Utara, Kab - 3327", "");
		dati2Map.put("Nias, Kab. - 3311", "");
		dati2Map.put("Nunukan, Kab. - 5409", "");
		dati2Map.put("Ogan Ilir, Kab - 3616", "");
		dati2Map.put("Ogan Komering Ilir, Kab. - 3611", "");
		dati2Map.put("Ogan Komering Ulu Selatan, Kab - 3614", "");
		dati2Map.put("Ogan Komering Ulu Timur, Kab - 3615", "");
		dati2Map.put("Ogan Komering Ulu, Kab. - 3607", "");
		dati2Map.put("Pacitan, Kab. - 1226", "");
		dati2Map.put("Padang Lawas Utara, Kab - 3323", "");
		dati2Map.put("Padang Lawas, Kab - 3322", "");
		dati2Map.put("Padang Panjang, Kota. - 3494", "");
		dati2Map.put("Padang Pariaman, Kab. - 3405", "");
		dati2Map.put("Padang Sidempuan, Kota. - 3399", "");
		dati2Map.put("Pagar Alam, Kota. - 3697", "");
		dati2Map.put("Pakpak Barat, Kab - 3317", "");
		dati2Map.put("Palangkaraya, Kota. - 5892", "");
		dati2Map.put("Palopo, Kota. - 6193", "");
		dati2Map.put("Pamekasan, Kab. - 1206", "");
		dati2Map.put("Pandeglang, Kab. - 0202", "");
		dati2Map.put("Pangkal Pinang, Kota. - 3791", "");
		dati2Map.put("Paniai, Kab. - 8212", "");
		dati2Map.put("Pare-Pare, Kota. - 6192", "");
		dati2Map.put("Pariaman, Kota. - 3497", "");
		dati2Map.put("Parigi Moutong, Kab. - 6009", "");
		dati2Map.put("Parimo/Banggai, Kab. - 6003", "");
		dati2Map.put("Pasaman Barat, Kab - 3410", "");
		dati2Map.put("Pasaman, Kab. - 3402", "");
		dati2Map.put("Pasir, Kab. - 5403", "");
		dati2Map.put("Pasuruan, Kota. - 1294", "");
		dati2Map.put("Payakumbuh, Kota. - 3496", "");
		dati2Map.put("Pegunungan Bintang, Kab. - 8221", "");
		dati2Map.put("Pekalongan, Kab. - 0905", "");
		dati2Map.put("Pekalongan, Kota. - 0993", "");
		dati2Map.put("Penajam Paser Utara, Kab. - 5411", "");
		dati2Map.put("Pesawaran, Kab - 3909", "");
		dati2Map.put("Pesisir Selatan, Kab. - 3406", "");
		dati2Map.put("Pide Jaya, Kab - 3218", "");
		dati2Map.put("Pidie, Kab. - 3202", "");
		dati2Map.put("Pinrang, Kab. - 6101", "");
		dati2Map.put("Pohuwato, Kab. - 6304", "");
		dati2Map.put("Polewali Mandar, Kab. - 6401", "");
		dati2Map.put("Poso, Kab. - 6002", "");
		dati2Map.put("Prabumulih, Kota. - 3694", "");
		dati2Map.put("Probolinggo, Kab. - 1215", "");
		dati2Map.put("Pulang Pisau, Kab. - 5809", "");
		dati2Map.put("Pulau Morotai, Kab - 8308", "");
		dati2Map.put("Puncak Jaya, Kab. - 8216", "");
		dati2Map.put("Puncak, Kab. - 8238", "");
		dati2Map.put("Purwakarta, Kab. - 0103", "");
		dati2Map.put("Raja Ampat, Kab. - 8405", "");
		dati2Map.put("Rejang Lebong, Kab. - 2303", "");
		dati2Map.put("Rokan Hilir, Kab. - 3509", "");
		dati2Map.put("Rokan Hulu, Kab. - 3508", "");
		dati2Map.put("Rote, Kab. - 7414", "");
		dati2Map.put("Sabang, Kota. - 3292", "");
		dati2Map.put("Sabu Raijua, Kab - 7420", "");
		dati2Map.put("Samosir, Kab - 3318", "");
		dati2Map.put("Sampang, Kab. - 1205", "");
		dati2Map.put("Sanggau, Kab. - 5304", "");
		dati2Map.put("Sangihe, Kab. - 6204", "");
		dati2Map.put("Sarmi, Kab. - 8217", "");
		dati2Map.put("Sarolangun, Kab. - 3104", "");
		dati2Map.put("Sawahlunto, Kota. - 3493", "");
		dati2Map.put("Sekadau, Kab. - 5309", "");
		dati2Map.put("Seluma, Kab - 2307", "");
		dati2Map.put("Seram Bagian Barat, Kota. - 8105", "");
		dati2Map.put("Seram Bagian Timur, Kota. - 8106", "");
		dati2Map.put("Seruyan, Kab. - 5810", "");
		dati2Map.put("Sibolga, Kota. - 3395", "");
		dati2Map.put("Sidenreng Rappang, Kab. - 6117", "");
		dati2Map.put("Sigi, Kab - 6010", "");
		dati2Map.put("Sijunjung, Kab - 3408", "");
		dati2Map.put("Sikka, Kab. - 7407", "");
		dati2Map.put("Simalungun, Kab. - 3304", "");
		dati2Map.put("Simeuleu, Kab - 3216", "");
		dati2Map.put("Sinjai, Kab. - 6110", "");
		dati2Map.put("Sintang, Kab. - 5305", "");
		dati2Map.put("Situbondo, Kab. - 1230", "");
		dati2Map.put("Solok Selatan, Kab. - 3404", "");
		dati2Map.put("Solok, Kab - 3412", "");
		dati2Map.put("Solok, Kota. - 3495", "");
		dati2Map.put("Soppeng, Kab (d/h Watansoppeng) - 6119", "");
		dati2Map.put("Sorong selatan, Kab. - 8404", "");
		dati2Map.put("Sorong, Kab. - 8401", "");
		dati2Map.put("Sorong, Kota. - 8491", "");
		dati2Map.put("Sragen, Kab. - 0925", "");
		dati2Map.put("Subulussalam - 3219", "");
		dati2Map.put("Sukabumi, Kab. - 0109", "");
		dati2Map.put("Sukabumi, Kota. - 0193", "");
		dati2Map.put("Sukamara, Kab. - 5812", "");
		dati2Map.put("Sumba Barat Daya, Kab. - 7417", "");
		dati2Map.put("Sumba Barat, Kab. - 7412", "");
		dati2Map.put("Sumba Tengah, Kab. - 7416", "");
		dati2Map.put("Sumba Timur, Kab. - 7411", "");
		dati2Map.put("Sumbawa Barat, Kab. - 7107", "");
		dati2Map.put("Sumedang, Kab. - 0112", "");
		dati2Map.put("Sumenep, Kab. - 1207", "");
		dati2Map.put("Supiori,Kab. - 8231", "");
		dati2Map.put("Tana Tidung, Kab. - 5412", "");
		dati2Map.put("Tana Toraja, Kab. - 6106", "");
		dati2Map.put("Tanah Bumbu, Kab. - 5110", "");
		dati2Map.put("Tanah Datar, Kab. - 3407", "");
		dati2Map.put("Tanah Laut, Kab. - 5102", "");
		dati2Map.put("Tanggamus, Kab. - 3906", "");
		dati2Map.put("Tanjung Balai, Kota. - 3394", "");
		dati2Map.put("Tanjung Jabung Barat, Kab. - 3107", "");
		dati2Map.put("Tanjung Jabung Timur, Kab. - 3108", "");
		dati2Map.put("Tapanuli Selatan, Kab. - 3310", "");
		dati2Map.put("Tapanuli Tengah, Kab. - 3309", "");
		dati2Map.put("Tapanuli Utara, Kab. - 3308", "");
		dati2Map.put("Tapin, Kab. - 5103", "");
		dati2Map.put("Tasikmalaya, Kab. - 0113", "");
		dati2Map.put("Tebing Tinggi, Kota. - 3391", "");
		dati2Map.put("Tebo, Kab. - 3109", "");
		dati2Map.put("Teluk Bintuni, Kab. - 8407", "");
		dati2Map.put("Teluk Wondama, Kab. - 8408", "");
		dati2Map.put("Tembrauw, Kab - 8409", "");
		dati2Map.put("Ternate, Kota. - 8390", "");
		dati2Map.put("Tidore Kepulauan, Kota. - 8391", "");
		dati2Map.put("Timor-Tengah Selatan, Kab. - 7402", "");
		dati2Map.put("Timor-Tengah Utara, Kab. - 7403", "");
		dati2Map.put("Toba Samosir, Kab. - 3313", "");
		dati2Map.put("Tojo Una-Una, Kab. - 6008", "");
		dati2Map.put("Tolikara, Kab. - 8223", "");
		dati2Map.put("Toli-Toli, Kab. - 6004", "");
		dati2Map.put("Toraja Utara, Kab - 6125", "");
		dati2Map.put("Trenggalek, Kab. - 1220", "");
		dati2Map.put("Tual, Kota. - 8192", "");
		dati2Map.put("Tuban, Kab. - 1228", "");
		dati2Map.put("Tulang Bawang Barat, Kab - 3911", "");
		dati2Map.put("Wajo, Kab. - 6103", "");
		dati2Map.put("Wakatobi, Kab. - 6905", "");
		dati2Map.put("Waropen, Kab. - 8224", "");
		dati2Map.put("Way Kanan, Kab. - 3908", "");
		dati2Map.put("Wonosobo, Kab. - 0920", "");
		dati2Map.put("Yahukimo, Kab. - 8222", "");
		dati2Map.put("Yalimo, Kab. - 8237", "");
	}
	
	public static DataMapping get() {
		if (dataMapping == null) dataMapping = new DataMapping();
		return dataMapping;
	}
	
	public String getDati2Mapping(String dati2) {
		return dati2Map.get(dati2);
	}
}