package com.btpn.migration.los.constant;

import java.util.HashMap;
import java.util.Map;

public class DataMapping {

	// Cara ambil dari excel
	// Cari sumbernya dari Data.Validity dapat Dati_3
	// Ketik names define Dati_3 akan mengarah ke Sheet Dati_3
	// Lalu pilih Data Consilidate akan muncul copy to $Value.$AX1
	// Buat sheet baru lalu copy $Value.$AX1 copy aja ke bawah
	
	private Map<String, String> dati2Map = new HashMap<String, String>();
	
	private static DataMapping dataMapping = null;
	
	private DataMapping() {		
		//Mapping Dari Dati2 yang ada di excel (InformasiDebitur.H121) ke  CommonService TypeCity
		dati2Map.put("Bekasi, Kab. - 0102", "KAB. BEKASI");
		dati2Map.put("Ambon, Kota. - 8191", "KOTA AMBON");
		dati2Map.put("Badung, Kab. - 7204", "KAB. BANDUNG");
		dati2Map.put("Balikpapan, Kota. - 5492", "KOTA BALIKPAPAN");
		dati2Map.put("Bandar Lampung, Kota. - 3991", "KOTA BANDAR LAMPUNG");
		dati2Map.put("Bandung Barat, Kab - 0122", "KAB. BANDUNG BARAT");
		dati2Map.put("Bandung, Kab. - 0111", "KAB. BANDUNG");
		dati2Map.put("Bandung, Kota. - 0191", "KOTA BANDUNG");
		dati2Map.put("Bandung, Kota. - 0192", "KOTA BANDUNG");
		dati2Map.put("Banggai Kepulauan, Kab - 6005", "KAB. BANGGAI KEPULAUAN");
		dati2Map.put("Bangka Belitung, Kab - 3707", "");
		dati2Map.put("Banjar, Kab. - 5101", "KAB. BANJAR");
		dati2Map.put("Banjarbaru, Kota. - 5192", "KOTA BANJARBARU");
		dati2Map.put("Banjarmasin, Kota. - 5191", "KOTA BANJARMASIN");
		dati2Map.put("Bantul, Kab. - 0501", "KAB. BANTUL");
		dati2Map.put("Banyumas, Kab. - 0914", "KAB. BANYUMAS");
		dati2Map.put("Banyuwangi, Kab. - 1211", "KAB. BANYUWANGI");
		dati2Map.put("Batam, Kota - 3892", "KOTA BATAM");
		dati2Map.put("Batang, Kab. - 0929", "KAB. BATANG");
		dati2Map.put("Batanghari, Kab. - 3101", "KAB. BATANGHARI");
		dati2Map.put("Batu, Kota. - 1271", "KOTA BATU");
		dati2Map.put("Bekasi, Kota. - 0198", "KOTA BEKASI");
		dati2Map.put("Belu, Kab. - 7404", "KAB. BELU");
		dati2Map.put("Bengkalis, Kab. - 3502", "KAB. BENGKALIS");
		dati2Map.put("Binjai, Kota. - 3392", "KOTA BINJAI");
		dati2Map.put("Binjai, Kota. - 3393", "KOTA BINJAI");
		dati2Map.put("Blora, Kab. - 0913", "KAB. BLORA");
		dati2Map.put("Bogor, Kab. - 0108", "KAB. BOGOR");
		dati2Map.put("Bogor, Kota. - 0192", "KOTA BOGOR");
		dati2Map.put("Bogor, Kota. - 0193", "KOTA BOGOR");
		dati2Map.put("Bogor, Kota. - 0194", "KOTA BOGOR");
		dati2Map.put("Bombana, Kab. - 6908", "KAB. BOMBANA");
		dati2Map.put("Bulukumba, Kab. - 6111", "KAB. BULUKUMBA");
		dati2Map.put("Cilacap, Kab. - 0915", "KAB. CILACAP");
		dati2Map.put("Cilegon, Kota. - 0291", "KOTA CILEGON");
		dati2Map.put("Cimahi, Kota. - 0196", "KOTA CIMAHI");
		dati2Map.put("Cirebon, Kab. - 0116", "KAB. CIREBON");
		dati2Map.put("Cirebon, Kota. - 0194", "KOTA CIREBON");
		dati2Map.put("Deli Serdang, Kab. - 3301", "KAB. DELI SERDANG");
		dati2Map.put("Demak, Kab. - 0903", "KAB. DEMAK");
		dati2Map.put("Denpasar, Kota. - 7291", "KOTA DENPASAR");
		dati2Map.put("Depok, Kota. - 0197", "KOTA DEPOK");
		dati2Map.put("Gianyar, Kab. - 7205", "KAB. GIANYAR");
		dati2Map.put("Gorontalo, Kota. - 6391", "KOTA GORONTALO");
		dati2Map.put("Gowa, Kab. - 6102", "KAB. GOWA");
		dati2Map.put("Gresik, Kab. - 1201", "KAB. GRESIK");
		dati2Map.put("Grobogan, Kab. - 0904", "KAB. GROBOGAN");
		dati2Map.put("Jakarta Barat, Wil. Kota - 0393", "KOTA ADM. JAKARTA BARAT");
		dati2Map.put("Jakarta Barat, Wil. Kota - 0394", "KOTA ADM. JAKARTA BARAT");
		dati2Map.put("Jakarta Barat, Wil. Kota - 0395", "KOTA ADM. JAKARTA BARAT");
		dati2Map.put("Jakarta Pusat, Wil. Kota - 0391", "KOTA ADM. JAKARTA PUSAT");
		dati2Map.put("Jakarta Pusat, Wil. Kota - 0392", "KOTA ADM. JAKARTA PUSAT");
		dati2Map.put("Jakarta Pusat, Wil. Kota - 0393", "KOTA ADM. JAKARTA PUSAT");
		dati2Map.put("Jakarta Selatan, Wil. Kota - 0394", "KOTA ADM. JAKARTA SELATAN");
		dati2Map.put("Jakarta Timur, Wil. Kota - 0395", "KOTA ADM. JAKARTA TIMUR");
		dati2Map.put("Jakarta Timur, Wil. Kota - 0396", "KOTA ADM. JAKARTA TIMUR");
		dati2Map.put("Jakarta Utara ., Wil. Kota - 0392", "KOTA ADM. JAKARTA UTARA");
		dati2Map.put("Jambi, Kota. - 3191", "KOTA JAMBI");
		dati2Map.put("Jember, Kab. - 1212", "KAB. JEMBER");
		dati2Map.put("Jembrana, Kab. - 7202", "KAB. JEMBRANA");
		dati2Map.put("Jepara, Kab. - 0911", "KAB. JEPARA");
		dati2Map.put("Kampar, Kab. - 3501", "KAB. KAMPAR");
		dati2Map.put("Karanganyar, Kab. - 0927", "KAB. KARANGANYAR");
		dati2Map.put("Karawang, Kab. - 0106", "KAB. KARAWANG");
		dati2Map.put("Kediri, Kota. - 1297", "KOTA KEDIRI");
		dati2Map.put("Kendal, Kab. - 0902", "KAB. KENDAL");
		dati2Map.put("Kendari, Kota. - 6991", "KOTA KENDARI");
		dati2Map.put("Ketapang, Kab. - 5303", "KAB. KETAPANG");
		dati2Map.put("Konawe, Kab. - 6906", "KAB. KONAWE");
		dati2Map.put("Kota Tangerang Selatan - 0294", "KOTA TANGERANG SELATAN");
		dati2Map.put("Kotawaringin Timur, Kab. - 5803", "KAB. KOTAWARINGIN TIMUR");
		dati2Map.put("Kubu Raya, Kab. - 5312", "KAB. KUBU RAYA");
		dati2Map.put("Kudus, Kab. - 0909", "KAB. KUDUS");
		dati2Map.put("Kuningan, Kab. - 0117", "KAB. KUNINGAN");
		dati2Map.put("Kupang, Kota. - 7491", "KOTA KUPANG");
		dati2Map.put("Labuhan Batu, Kab. - 3305", "KAB. LABUHANBATU");
		dati2Map.put("Lampung Selatan, Kab. - 3901", "KAB. LAMPUNG SELATAN");
		dati2Map.put("Lampung Timur, Kab. - 3907", "KAB. LAMPUNG TIMUR");
		dati2Map.put("Lampung Utara, Kab. - 3903", "KAB. LAMPUNG UTARA");
		dati2Map.put("Langkat, Kab. - 3302", "KAB. LANGKAT");
		dati2Map.put("Lombok Tengah, Kab. - 7102", "KAB. LOMBOK TENGAH");
		dati2Map.put("Luwu, Kab. - 6109", "KAB. LUWU");
		dati2Map.put("Madiun, Kab. - 1222", "KAB. MADIUN");
		dati2Map.put("Madiun, Kota. - 1298", "KOTA MADIUN");
		dati2Map.put("Magelang, Kab. - 0918", "KAB. MAGELANG");
		dati2Map.put("Magelang, Kota. - 0995", "KOTA MAGELANG");
		dati2Map.put("Majalengka, Kab. - 0119", "KAB. MAJALENGKA");
		dati2Map.put("Makassar, Kota. - 6191", "KOTA MAKASSAR");
		dati2Map.put("Malang, Kab. - 1213", "KAB. MALANG");
		dati2Map.put("Malang, Kota. - 1293", "KOTA MALANG");
		dati2Map.put("Malang, Kota. - 1294", "KOTA MALANG");
		dati2Map.put("Malinau, Kab. - 5410", "KAB. MALINAU");
		dati2Map.put("Maros, Kab. - 6107", "KAB. MAROS");
		dati2Map.put("Mataram, Kota. - 7191", "KOTA MATARAM");
		dati2Map.put("Medan, Kota. - 3396", "KOTA MEDAN");
		dati2Map.put("Medan, Kota. - 3397", "KOTA MEDAN");
		dati2Map.put("Menado, Kota. - 6291", "KOTA MANADO");
		dati2Map.put("Metro, Kota. - 3992", "KOTA METRO");
		dati2Map.put("Minahasa, Kab. - 6202", "KAB. MINAHASA");
		dati2Map.put("Mojokerto, Kab. - 1203", "KAB. MOJOKERTO");
		dati2Map.put("Mojokerto, Kota. - 1292", "KOTA MOJOKERTO");
		dati2Map.put("Padang, Kota. - 3492", "KOTA PADANG");
		dati2Map.put("Palembang, Kota. - 3691", "KOTA PALEMBANG");
		dati2Map.put("Palu, Kota. - 6091", "KOTA PALU");
		dati2Map.put("Pangkajene Kepulauan, Kab. - 6118", "KAB. PANGKAJENE KEPULAUAN");
		dati2Map.put("Pasuruan, Kab. - 1214", "KAB. PASURUAN");
		dati2Map.put("Pati, Kab. - 0908", "KAB. PATI");
		dati2Map.put("Pekanbaru, Kota. - 3591", "KOTA PEKANBARU");
		dati2Map.put("Pelalawan, Kab. - 3510", "KAB. PELALAWAN");
		dati2Map.put("Pemalang, Kab. - 0910", "KAB. PEMALANG");
		dati2Map.put("Pematang Siantar, Kota. - 3393", "KOTA PEMATANG SIANTAR");
		dati2Map.put("Ponorogo, Kab. - 1225", "KAB. PONOROGO");
		dati2Map.put("Pontianak, Kab. - 5301", "");
		dati2Map.put("Pontianak, Kota. - 5391", "KOTA PONTIANAK");
		dati2Map.put("Pontianak, Kota. - 5392", "KOTA PONTIANAK");
		dati2Map.put("Pringsewu, Kab - 3910", "KAB. PRINGSEWU");
		dati2Map.put("Probolinggo, Kota. - 1295", "KOTA PROBOLINGGO");
		dati2Map.put("Purbalingga, Kab. - 0916", "KAB. PURBALINGGA");
		dati2Map.put("Purworejo, Kab. - 0921", "KAB. PURWOREJO");
		dati2Map.put("Rembang, Kab. - 0912", "KAB. REMBANG");
		dati2Map.put("Salatiga, Kota. - 0992", "KOTA SALATIGA");
		dati2Map.put("Samarinda, Kota. - 5491", "KOTA SAMARINDA");
		dati2Map.put("Samarinda, Kota. - 5492", "KOTA SAMARINDA");
		dati2Map.put("Sambas, Kab. - 5302", "KAB. SAMBAS");
		dati2Map.put("Selayar, Kab. - 6114", "KAB. KEPULAUAN SELAYAR");
		dati2Map.put("Semarang, Kab. - 0901", "KAB. SEMARANG");
		dati2Map.put("Semarang, Kota. - 0991", "KOTA SEMARANG");
		dati2Map.put("Semarang, Kota. - 0992", "KOTA SEMARANG");
		dati2Map.put("Serang, Kab. - 0203", "KAB. SERANG");
		dati2Map.put("Serang. Kota. - 0293", "KOTA SERANG");
		dati2Map.put("Serdang Bedagai, Kab - 3319", "KAB. SERDANG BEDAGAI");
		dati2Map.put("Siak, Kab. - 3511", "KAB. SIAK");
		dati2Map.put("Sidoarjo, Kab. - 1202", "KAB. SIDOARJO");
		dati2Map.put("Singkawang, Kota. - 5392", "KOTA SINGKAWANG");
		dati2Map.put("Sleman, Kab. - 0502", "KAB. SLEMAN");
		dati2Map.put("Subang, Kab. - 0121", "KAB. SUBANG");
		dati2Map.put("Sukoharjo, Kab. - 0926", "KAB. SUKOHARJO");
		dati2Map.put("Sumbawa, Kab. - 7104", "KAB. SUMBAWA");
		dati2Map.put("Surabaya, Kota. - 1291", "KOTA SURABAYA");
		dati2Map.put("Surabaya, Kota. - 1292", "KOTA SURABAYA");
		dati2Map.put("Surakarta, Kota. - 0996", "KOTA SURAKARTA");
		dati2Map.put("Tabalong, Kab. - 5109", "KAB. TABALONG");
		dati2Map.put("Tabanan, Kab. - 7203", "KAB. TABANAN");
		dati2Map.put("Takalar, Kab. - 6115", "KAB. TAKALAR");
		dati2Map.put("Tangerang, Kab. - 0204", "KAB. TANGERANG");
		dati2Map.put("Tangerang, Kota. - 0292", "KOTA TANGERANG");
		dati2Map.put("Tangerang, Kota. - 0293", "KOTA TANGERANG");
		dati2Map.put("Tangerang, Kota. - 0294", "KOTA TANGERANG");
		dati2Map.put("Tanjungpinang, Kota - 3891", "KOTA TANJUNG PINANG");
		dati2Map.put("Tarakan, Kota. - 5493", "KOTA TARAKAN");
		dati2Map.put("Tasikmalaya, Kota. - 0195", "KOTA TASIKMALAYA");
		dati2Map.put("Tasikmalaya, Kota. - 0196", "KOTA TASIKMALAYA");
		dati2Map.put("Tasikmalaya, Kota. - 0197", "KOTA TASIKMALAYA");
		dati2Map.put("Tegal, Kab. - 0906", "KAB. TEGAL");
		dati2Map.put("Tegal, Kota. - 0994", "KOTA TEGAL");
		dati2Map.put("Temanggung, Kab. - 0919", "KAB. TEMANGGUNG");
		dati2Map.put("Tomohon, Kota - 6294", "KOTA TOMOHON");
		dati2Map.put("Tulang Bawang, Kab. - 3905", "KAB. TULANG BAWANG");
		dati2Map.put("Tulungagung, Kab. - 1219", "KAB. TULUNGAGUNG");
		dati2Map.put("Wonogiri, Kab. - 0928", "KAB. WONOGIRI");
		dati2Map.put("Yapen-Waropen, Kab. - 8210", "KAB. WAROPEN");
		dati2Map.put("Yogyakarta, Kota. - 0591", "KOTA YOGYAKARTA");
		
		// Unmapping
		dati2Map.put("Aceh Barat Daya, Kab. - 3213","KAB. ACEH BARAT DAYA");
		dati2Map.put("Aceh Barat, Kab. - 3206","KAB. ACEH BARAT");
		dati2Map.put("Besar, Kab. - 3201","KAB. ACEH BESAR");
		dati2Map.put("Aceh Jaya, Kab. - 3214","KAB. ACEH JAYA");
		dati2Map.put("Aceh Jeumpa/Bireuen, Kab. - 3210","KAB. BIREUEN");
		dati2Map.put("Aceh Selatan, Kab. - 3205","KAB. ACEH SELATAN");
		dati2Map.put("Aceh Singkil, Kab. - 3209","KAB. ACEH SINGKIL");
		dati2Map.put("Aceh Tamiang, Kab. - 3211","KAB. ACEH TAMIANG");
		dati2Map.put("Aceh Tengah, Kab. - 3207","KAB. ACEH TENGAH");
		dati2Map.put("Aceh Tenggara, Kab. - 3208","KAB. ACEH TENGGARA");
		dati2Map.put("Aceh Timur, Kab. - 3204","KAB. ACEH TIMUR");
		dati2Map.put("Aceh Utara, Kab. - 3203","KAB. ACEH UTARA");
		dati2Map.put("Agam, Kab. - 3401","KAB. AGAM");
		dati2Map.put("Alor, Kab. - 7405","KAB. ALOR");
		dati2Map.put("Anambas, Kab - 3805","KAB. KEPULAUAN ANAMBAS");
		dati2Map.put("Angkola Sipirok, Kab - 3320","");
		dati2Map.put("Asahan, Kab. - 3306","KAB. ASAHAN");
		dati2Map.put("Asmat, Kab. - 8228","KAB. ASMAT");
		dati2Map.put("Balangan, Kab. - 5111", "KAB. BALANGAN");
		dati2Map.put("Banda Aceh, Kota. - 3291", "KOTA BANDA ACEH");
		dati2Map.put("Bangka Barat, Kab - 3703", "KAB. BANGKA BARAT");
		dati2Map.put("Bangka Selatan, Kab - 3704", "KAB. BANGKA SELATAN");
		dati2Map.put("Bangka Tengah, Kab - 3705", "KAB. BANGKA TENGAH");
		dati2Map.put("Bangka, Kab. - 3701", "KAB. BANGKA");
		dati2Map.put("Bangkalan, Kab. - 1208", "KAB. BANGKALAN");
		dati2Map.put("Bangli, Kab. - 7207", "KAB. BANGLI");
		dati2Map.put("Banjar, Kota. - 0180", "KAB. BANJAR");
		dati2Map.put("Banjarnegara, Kab. - 0917", "KAB. BANJARNEGARA");
		dati2Map.put("Bantaeng, Kab. - 6112", "KAB. BANTAENG");
		dati2Map.put("Banyuasin, Kab - 3613", "KAB. BANYUASIN");
		dati2Map.put("Barito Kuala, Kab. - 5107", "KAB. BARITO KUALA");
		dati2Map.put("Barito Selatan, Kab. - 5806", "KAB. BARITO SELATAN");
		dati2Map.put("Barito Timur, Kab. - 5805", "KAB. BARITO TIMUR");
		dati2Map.put("Barito Utara, Kab. - 5808", "KAB. BARITO UTARA");
		dati2Map.put("Barru, Kab. - 6116", "KAB. BARRU");
		dati2Map.put("Batu Bara, Kab - 3321", "KAB. BATU BARA");
		dati2Map.put("Bau-Bau,Kota. - 6990", "KOTA BAUBAU");
		dati2Map.put("Belitung Timur, Kab - 3706", "KAB. BELITUNG TIMUR");
		dati2Map.put("Belitung, Kab. - 3702", "KAB. BELITUNG");
		dati2Map.put("Bener Meriah, Kab - 3217", "KAB. BENER MERIAH");
		dati2Map.put("Bengkayang, Kab. - 5307", "KAB. BENGKAYANG");
		dati2Map.put("Bengkulu Selatan, Kab. - 2301", "KAB. BENGKULU SELATAN");
		dati2Map.put("Bengkulu Tengah, Kab - 2309", "KAB. BENGKULU TENGAH");
		dati2Map.put("Bengkulu Utara, Kab. - 2302", "KAB. BENGKULU UTARA");
		dati2Map.put("Bengkulu, Kota. - 2391", "KOTA BENGKULU");
		dati2Map.put("Berau, Kab. - 5402", "KAB. BERAU");
		dati2Map.put("Biak Numfor, Kab. - 8202", "KAB. BIAK NUMFOR");
		dati2Map.put("Bima, Kab. - 7105", "KAB. BIMA");
		dati2Map.put("Bintan, Kab (d/h Kab. Kepulauan Riau - 3804", "KAB. BINTAN");
		dati2Map.put("Bitung, Kota. - 6293", "KOTA BITUNG");
		dati2Map.put("Blitar, Kab. - 1221", "KAB. BLITAR");
		dati2Map.put("Blitar, Kota. - 1296", "KOTA BLITAR");
		dati2Map.put("Bojonegoro, Kab. - 1227", "KAB. BOJONEGORO");
		dati2Map.put("Bolaang Mongondow Selatan, Kab - 6212", "KAB. BOLAANG MONGONDOW SELATAN");
		dati2Map.put("Bolaang Mongondow Timur, Kab - 6213", "KAB. BOLAANG MONGONDOW TIMUR");
		dati2Map.put("Bolaang Mongondow, Kab. - 6203", "KAB. BOLAANG MONGONDOW");
		dati2Map.put("Bolaang Mongoundow Utara, Kab. - 6210", "KAB. BOLAANG MONGONDOW UTARA");
		dati2Map.put("Bondowoso, Kab. - 1209", "KAB. BONDOWOSO");
		dati2Map.put("Bone, Kab. - 6105", "KAB. BONE");
		dati2Map.put("Bonebolango, Kab. - 6303", "KAB. BONE BOLANGO");
		dati2Map.put("Bontang, Kota. - 5494", "KOTA BONTANG");
		dati2Map.put("Boven Digoel, Kab. - 8226", "KAB. BOVEN DIGOEL");
		dati2Map.put("Boyolali, Kab. - 0924", "KAB. BOYOLALI");
		dati2Map.put("Brebes, Kab. - 0907", "KAB. BREBES");
		dati2Map.put("Bualemo, Kab. - 6302", "KAB. BOALEMO");
		dati2Map.put("Bukittinggi, Kota. - 3491", "KOTA BUKITTINGGI");
		dati2Map.put("Buleleng, Kab. - 7201", "KAB. BULELENG");
		dati2Map.put("Bulungan, Kab. - 5404", "KAB. BULUNGAN");
		dati2Map.put("Bungo, Kab - 3112", "KAB. BUNGO");
		dati2Map.put("Buol, Kab. - 6007", "KAB. BUOL");
		dati2Map.put("Buru Selatan, Kab - 8109", "KAB. BURU SELATAN");
		dati2Map.put("Buru, Kab - 8104", "KAB. BURU");
		dati2Map.put("Buton Utara, Kab. - 6910", "KAB. BUTON UTARA");
		dati2Map.put("Buton, Kab. - 6901", "KAB. BUTON");
		dati2Map.put("Ciamis, Kab. - 0115", "KAB. CIAMIS");
		dati2Map.put("Cianjur, Kab. - 0110", "KAB. CIANJUR");
		dati2Map.put("Dairi, Kab. - 3307", "KAB. DAIRI");
		dati2Map.put("Deiyai, Kab - 8240", "KAB. DEIYAI");
		dati2Map.put("Dharmasraya, Kab. - 3411", "KAB. DHARMASRAYA");
		dati2Map.put("DI  LUAR  INDONESIA - 9999", "");
		dati2Map.put("Dogiyai, Kab. - 8233", "KAB. DOGIYAI");
		dati2Map.put("Dompu, Kab. - 7106", "KAB. DOMPU");
		dati2Map.put("Donggala, Kab. - 6001", "KAB. DONGGALA");
		dati2Map.put("Dumai, Kota. - 3592", "KOTA DUMAI");
		dati2Map.put("Empat Lawang - 3617", "KAB. EMPAT LAWANG");
		dati2Map.put("Ende, Kab. - 7408", "KAB. ENDE");
		dati2Map.put("Enrekang, Kab. - 6121", "KAB. ENREKANG");
		dati2Map.put("Fak-Fak, Kab. - 8402", "KAB. FAK FAK");
		dati2Map.put("Flores Timur, Kab. - 7406", "KAB. FLORES TIMUR");
		dati2Map.put("Garut, Kab. - 0114", "KAB. GARUT");
		dati2Map.put("Gayo Luwes, Kab. - 3212", "KAB. GAYO LUES");
		dati2Map.put("Gorontalo Utara, Kab. - 6305", "KAB. GORONTALO UTARA");
		dati2Map.put("Gorontalo, Kab. - 6301", "KAB. GORONTALO");
		dati2Map.put("Gunung Kidul, Kab. - 0503", "KAB. GUNUNG KIDUL");
		dati2Map.put("Gunung Mas, Kab. - 5807", "KAB. GUNUNG MAS");
		dati2Map.put("Halmahera Barat, Kab. - 8305", "KAB. HALMAHERA BARAT");
		dati2Map.put("Halmahera Selatan, Kab. - 8306", "KAB. HALMAHERA SELATAN");
		dati2Map.put("Halmahera Tengah, Kab. - 8302", "KAB. HALMAHERA TENGAH");
		dati2Map.put("Halmahera Timur, Kab. - 8304", "KAB. HALMAHERA TIMUR");
		dati2Map.put("Halmahera Utara, Kab. - 8303", "KAB. HALMAHERA UTARA");
		dati2Map.put("Hulu Sungai Selatan, Kab. - 5104", "KAB. HULU SUNGAI SELATAN");
		dati2Map.put("Hulu Sungai Tengah, Kab. - 5105", "KAB. HULU SUNGAI TENGAH");
		dati2Map.put("Hulu Sungai Utara, Kab. - 5106", "KAB. HULU SUNGAI UTARA");
		dati2Map.put("Humbang Hasundutan, Kab - 3316", "KAB. HUMBANG HASUNDUTAN");
		dati2Map.put("Indragiri Hilir, Kab. - 3505", "KAB. INDRAGIRI HILIR");
		dati2Map.put("Indragiri Hulu, Kab. - 3504", "KAB. INDRAGIRI HULU");
		dati2Map.put("Indramayu, Kab. - 0118", "KAB. INDRAMAYU");
		dati2Map.put("Intan Jaya, Kab - 8239", "KAB. INTAN JAYA");
		dati2Map.put("Jayapura, Kab. - 8201", "KAB. JAYAPURA");
		dati2Map.put("Jayapura, Kota. - 8291", "KOTA JAYAPURA");
		dati2Map.put("Jayawijaya, Kab. - 8213", "KAB. JAYAWIJAYA");
		dati2Map.put("Jeneponto, Kab. - 6113", "KAB. JENEPONTO");
		dati2Map.put("Jombang, Kab. - 1204", "KAB. JOMBANG");
		dati2Map.put("Kaimana, Kab. - 8406", "KAB. KAIMANA");
		dati2Map.put("Kapuas Hulu, Kab. - 5306", "KAB. KAPUAS HULU");
		dati2Map.put("Kapuas, Kab. - 5801", "KAB. KAPUAS");
		dati2Map.put("Karangasem, Kab. - 7208", "KAB. KARANGASEM");
		dati2Map.put("Karimun, Kab - 3801", "KAB. KARIMUN");
		dati2Map.put("Karo, Kab. - 3303", "KAB. KARO");
		dati2Map.put("Katingan, Kab. - 5811", "KAB. KATINGAN");
		dati2Map.put("Kaur, Kab - 2308", "KAB. KAUR");
		dati2Map.put("Kayong Utara, Kab. - 5311", "KAB. KAYONG UTARA");
		dati2Map.put("Kebumen, Kab. - 0922", "KAB. KEBUMEN");
		dati2Map.put("Kediri, Kab. - 1217", "KAB. KEDIRI");
		dati2Map.put("Keerom, Kab. - 8218", "KAB. KEEROM");
		dati2Map.put("Kepahiang, Kab - 2305", "KAB. KEPAHIANG");
		dati2Map.put("Kepulauan Aru, Kota. - 8107", "KAB. KEPULAUAN ARU");
		dati2Map.put("Kepulauan Mentawai, Kab. - 3409", "KAB. KEPULAUAN MENTAWAI");
		dati2Map.put("Kepulauan Meranti, Kab - 3513", "KAB. KEPULAUAN MERANTI");
		dati2Map.put("Kepulauan Seribu, Wilayah - 0396", "KAB. ADM. KEP. SERIBU");
		dati2Map.put("Kepulauan Sitaro, Kab. - 6211", "");
		dati2Map.put("Kepulauan Sula, Kab. - 8307", "KAB. KEPULAUAN SULA");
		dati2Map.put("kepulauan Talaud, Kab. - 6205", "KAB. KEPULAUAN TALAUD");
		dati2Map.put("Kerinci, Kab. - 3105", "KAB. KERINCI");
		dati2Map.put("Klaten, Kab. - 0923", "KAB. KLATEN");
		dati2Map.put("Klungkung, Kab. - 7206", "KAB. KLUNGKUNG");
		dati2Map.put("Kolaka Utara, Kab. - 6909", "KAB. KOLAKA UTARA");
		dati2Map.put("Kolaka, Kab. - 6904", "KAB. KOLAKA");
		dati2Map.put("Konawe Selatan, Kab. - 6907", "KAB. KONAWE SELATAN");
		dati2Map.put("Konawe Utara, Kab. - 6911", "KAB. KONAWE UTARA");
		dati2Map.put("Kota Baru, Kab. - 5108", "KAB. KOTABARU");
		dati2Map.put("Kota Gunung Sitoli - 3397", "KOTA GUNUNGSITOLI");
		dati2Map.put("Kota Sungai Penuh - 3192", "KOTA SUNGAI PENUH");
		dati2Map.put("Kota. Bima - 7192", "KOTA BIMA");
		dati2Map.put("Kota. Tomohon - 6294", "KOTA TOMOHON");
		dati2Map.put("Kotamobagu, Kota. - 6292", "KOTA KOTAMOBAGU");
		dati2Map.put("Kotawaringin Barat, Kab. - 5802", "KAB. KOTAWARINGIN BARAT");
		dati2Map.put("Kuantan Singingi, Kab. - 3512", "KAB. KUANTAN SINGINGI");
		dati2Map.put("Kulon Progo, Kab. - 0504", "KAB. KULON PROGO");
		dati2Map.put("Kupang, Kab. - 7401", "KAB. KUPANG");
		dati2Map.put("Kutai Barat, Kab. - 5405", "KAB. KUTAI BARAT");
		dati2Map.put("Kutai Kartanegara, Kab. - 5401", "KAB. KUTAI KARTANEGARA");
		dati2Map.put("Kutai Timur, Kab. - 5406", "KAB. KUTAI TIMUR");
		dati2Map.put("Labuanbatu Selatan, Kab - 3324", "KAB. LABUHANBATU SELATAN");
		dati2Map.put("Labuanbatu Utara, Kab - 3325", "KAB. LABUHANBATU UTARA");
		dati2Map.put("Lahat, Kab. - 3609", "KAB. LAHAT");
		dati2Map.put("Lamandau, Kab. - 5813", "KAB. LAMANDAU");
		dati2Map.put("Lamongan, Kab. - 1229", "KAB. LAMONGAN");
		dati2Map.put("Lampung Barat, Kab. - 3904", "KAB. LAMPUNG BARAT");
		dati2Map.put("Lampung Tengah, Kab. - 3902", "KAB. LAMPUNG TENGAH");
		dati2Map.put("Landak, Kab. - 5308", "KAB. LANDAK");
		dati2Map.put("Langsa, Kota. - 3294", "KOTA LANGSA");
		dati2Map.put("Lanny Jaya, Kab. - 8234", "KAB. LANNY JAYA");
		dati2Map.put("Lebak, Kab. - 0201", "KAB. LEBAK");
		dati2Map.put("Lebong, Kab - 2304", "KAB. LEBONG");
		dati2Map.put("Lematang Ilir Ogan Tengah (Muara Enim), Kab. - 3608", "");
		dati2Map.put("Lembata, Kab. - 7413", "KAB. LEMBATA");
		dati2Map.put("Lhokseumawe, Kota. - 3293", "KOTA LHOKSEUMAWE");
		dati2Map.put("Limapuluh Koto, Kab. - 3403", "KAB. LIMA PULUH KOTA");
		dati2Map.put("Lingga, Kab - 3802", "KAB. LINGGA");
		dati2Map.put("Lombok Barat, Kab. - 7101", "KAB. LOMBOK BARAT");
		dati2Map.put("Lombok Timur, Kab. - 7103", "KAB. LOMBOK TIMUR");
		dati2Map.put("Lombok Utara, Kab - 7108", "KAB. LOMBOK UTARA");
		dati2Map.put("Lubuklinggau, Kota. - 3693", "KOTA LUBUK LINGGAU");
		dati2Map.put("Lumajang, Kab. - 1216", "KAB. LUMAJANG");
		dati2Map.put("Luwu Timur, Kab (d/h Luwu Selatan) - 6122", "KAB. LUWU TIMUR");
		dati2Map.put("Luwu Utara, Kab. - 6124", "KAB. LUWU UTARA");
		dati2Map.put("Magetan, Kab. - 1224", "KAB. MAGETAN");
		dati2Map.put("Majene, Kab. - 6402", "KAB. MAJENE");
		dati2Map.put("Maluku Barat Daya, Kab - 8108", "KAB. MALUKU BARAT DAYA");
		dati2Map.put("Maluku Tengah, Kab. - 8101", "KAB. MALUKU TENGAH");
		dati2Map.put("Maluku Tenggara Barat, Kab. - 8103", "KAB. MALUKU TENGGARA BARAT");
		dati2Map.put("Maluku Tenggara, Kab. - 8102", "KAB. MALUKU TENGGARA");
		dati2Map.put("Mamasa, Kab. - 6403", "KAB. MAMASA");
		dati2Map.put("Mamberamo Raya, Kab. - 8232", "KAB. MAMBERAMO RAYA");
		dati2Map.put("Mamberamo Tengah, Kab. - 8235", "KAB. MAMBERAMO TENGAH");
		dati2Map.put("Mamuju Utara, Kab. - 6404", "KAB. MAMUJU UTARA");
		dati2Map.put("Mamuju, Kota. - 6491", "");
		dati2Map.put("Mandailing Natal, Kab. - 3314", "KAB. MANDAILING NATAL");
		dati2Map.put("Manggarai Barat, Kab. - 7415", "KAB. MANGGARAI BARAT");
		dati2Map.put("Manggarai Timur, Kab. - 7418", "KAB. MANGGARAI TIMUR");
		dati2Map.put("Manggarai, Kab. - 7410", "KAB. MANGGARAI");
		dati2Map.put("Manokwari, Kab. - 8403", "KAB. MANOKWARI");
		dati2Map.put("Mappi, Kab. - 8227", "KAB. MAPPI");
		dati2Map.put("Maybrat, Kab - 8410", "KAB. MAYBRAT");
		dati2Map.put("Melawi, Kab.. - 5310", "KAB. MELAWI");
		dati2Map.put("Merangin, Kab. - 3111", "KAB. MERANGIN");
		dati2Map.put("Merauke, Kab. - 8211", "KAB. MERAUKE");
		dati2Map.put("Mesuji, Kab - 3912", "KAB. MESUJI");
		dati2Map.put("Mimika, Kab. - 8215", "KAB. MIMIKA");
		dati2Map.put("Minahasa Selatan, Kab. - 6206", "KAB. MINAHASA SELATAN");
		dati2Map.put("Minahasa Tenggara, Kab. - 6209", "KAB. MINAHASA TENGGARA");
		dati2Map.put("Minahasa Utara, Kab. - 6207", "KAB. MINAHASA UTARA");
		dati2Map.put("Morowali, Kab. - 6006", "KAB. MOROWALI");
		dati2Map.put("Muaro Jambi, Kab. - 3106", "KAB. MUARO JAMBI");
		dati2Map.put("Mukomuko, Kab - 2306", "KAB. MUKOMUKO");
		dati2Map.put("Muna, Kab. - 6903", "KAB. MUNA");
		dati2Map.put("Murung Raya, Kab. - 5804", "KAB. MURUNG RAYA");
		dati2Map.put("Musi Banyuasin, Kab. - 3606", "KAB. MUSI BANYUASIN");
		dati2Map.put("Musi Rawas, Kab. - 3610", "KAB. MUSI RAWAS");
		dati2Map.put("Nabire, Kab. - 8214", "KAB. NABIRE");
		dati2Map.put("Nagan Raya, Kab. - 3215", "KAB. NAGAN RAYA");
		dati2Map.put("Nagekeo, Kab. - 7419", "KAB. NAGEKEO");
		dati2Map.put("Natuna, Kab - 3803", "KAB. NATUNA");
		dati2Map.put("Nduga Tengah, Kab. - 8236", "");
		dati2Map.put("Ngada, Kab. - 7409", "KAB. NGADA");
		dati2Map.put("Nganjuk, Kab. - 1218", "KAB. NGANJUK");
		dati2Map.put("Ngawi, Kab. - 1223", "KAB. NGAWI");
		dati2Map.put("Nias Barat, Kab - 3326", "KAB. NIAS BARAT");
		dati2Map.put("Nias Selatan, Kab - 3315", "KAB. NIAS SELATAN");
		dati2Map.put("Nias Utara, Kab - 3327", "KAB. NIAS UTARA");
		dati2Map.put("Nias, Kab. - 3311", "KAB. NIAS");
		dati2Map.put("Nunukan, Kab. - 5409", "KAB. NUNUKAN");
		dati2Map.put("Ogan Ilir, Kab - 3616", "KAB. OGAN ILIR");
		dati2Map.put("Ogan Komering Ilir, Kab. - 3611", "KAB. OGAN KOMERING ILIR");
		dati2Map.put("Ogan Komering Ulu Selatan, Kab - 3614", "KAB. OGAN KOMERING ULU SELATAN");
		dati2Map.put("Ogan Komering Ulu Timur, Kab - 3615", "KAB. OGAN KOMERING ULU TIMUR");
		dati2Map.put("Ogan Komering Ulu, Kab. - 3607", "KAB. OGAN KOMERING ULU");
		dati2Map.put("Pacitan, Kab. - 1226", "KAB. PACITAN");
		dati2Map.put("Padang Lawas Utara, Kab - 3323", "KAB. PADANG LAWAS UTARA");
		dati2Map.put("Padang Lawas, Kab - 3322", "KAB. PADANG LAWAS");
		dati2Map.put("Padang Panjang, Kota. - 3494", "KOTA PADANG PANJANG");
		dati2Map.put("Padang Pariaman, Kab. - 3405", "KAB. PADANG PARIAMAN");
		dati2Map.put("Padang Sidempuan, Kota. - 3399", "");
		dati2Map.put("Pagar Alam, Kota. - 3697", "KOTA PAGAR ALAM");
		dati2Map.put("Pakpak Barat, Kab - 3317", "KAB. PAKPAK BHARAT");
		dati2Map.put("Palangkaraya, Kota. - 5892", "KOTA PALANGKARAYA");
		dati2Map.put("Palopo, Kota. - 6193", "KOTA PALOPO");
		dati2Map.put("Pamekasan, Kab. - 1206", "KAB. PAMEKASAN");
		dati2Map.put("Pandeglang, Kab. - 0202", "KAB. PANDEGLANG");
		dati2Map.put("Pangkal Pinang, Kota. - 3791", "KOTA PANGKAL PINANG");
		dati2Map.put("Paniai, Kab. - 8212", "KAB. PANIAI");
		dati2Map.put("Pare-Pare, Kota. - 6192", "KOTA PAREPARE");
		dati2Map.put("Pariaman, Kota. - 3497", "KOTA PARIAMAN");
		dati2Map.put("Parigi Moutong, Kab. - 6009", "KAB. PARIGI MOUTONG");
		dati2Map.put("Parimo/Banggai, Kab. - 6003", "");
		dati2Map.put("Pasaman Barat, Kab - 3410", "KAB. PASAMAN BARAT");
		dati2Map.put("Pasaman, Kab. - 3402", "KAB. PASAMAN");
		dati2Map.put("Pasir, Kab. - 5403", "");
		dati2Map.put("Pasuruan, Kota. - 1294", "KOTA PASURUAN");
		dati2Map.put("Payakumbuh, Kota. - 3496", "KOTA PAYAKUMBUH");
		dati2Map.put("Pegunungan Bintang, Kab. - 8221", "KAB. PEGUNUNGAN BINTANG");
		dati2Map.put("Pekalongan, Kab. - 0905", "KAB. PEKALONGAN");
		dati2Map.put("Pekalongan, Kota. - 0993", "KOTA PEKALONGAN");
		dati2Map.put("Penajam Paser Utara, Kab. - 5411", "KAB. PENAJAM PASER UTARA");
		dati2Map.put("Pesawaran, Kab - 3909", "KAB. PESAWARAN");
		dati2Map.put("Pesisir Selatan, Kab. - 3406", "KAB. PESISIR SELATAN");
		dati2Map.put("Pide Jaya, Kab - 3218", "KAB. PIDIE JAYA");
		dati2Map.put("Pidie, Kab. - 3202", "KAB. PIDIE");
		dati2Map.put("Pinrang, Kab. - 6101", "KAB. PINRANG");
		dati2Map.put("Pohuwato, Kab. - 6304", "");
		dati2Map.put("Polewali Mandar, Kab. - 6401", "KAB. POLEWALI MANDAR");
		dati2Map.put("Poso, Kab. - 6002", "KAB. POSO");
		dati2Map.put("Prabumulih, Kota. - 3694", "KOTA PRABUMULIH");
		dati2Map.put("Probolinggo, Kab. - 1215", "KAB. PROBOLINGGO");
		dati2Map.put("Pulang Pisau, Kab. - 5809", "KAB. PULANG PISAU");
		dati2Map.put("Pulau Morotai, Kab - 8308", "KAB. PULAU MOROTAI");
		dati2Map.put("Puncak Jaya, Kab. - 8216", "KAB. PUNCAK JAYA");
		dati2Map.put("Puncak, Kab. - 8238", "KAB. PUNCAK");
		dati2Map.put("Purwakarta, Kab. - 0103", "KAB. PURWAKARTA");
		dati2Map.put("Raja Ampat, Kab. - 8405", "KAB. RAJA AMPAT");
		dati2Map.put("Rejang Lebong, Kab. - 2303", "KAB. REJANG LEBONG");
		dati2Map.put("Rokan Hilir, Kab. - 3509", "KAB. ROKAN HILIR");
		dati2Map.put("Rokan Hulu, Kab. - 3508", "KAB. ROKAN HULU");
		dati2Map.put("Rote, Kab. - 7414", "");
		dati2Map.put("Sabang, Kota. - 3292", "KOTA SABANG");
		dati2Map.put("Sabu Raijua, Kab - 7420", "KAB. SABU RAIJUA");
		dati2Map.put("Samosir, Kab - 3318", "KAB. SAMOSIR");
		dati2Map.put("Sampang, Kab. - 1205", "KAB. SAMPANG");
		dati2Map.put("Sanggau, Kab. - 5304", "KAB. SANGGAU");
		dati2Map.put("Sangihe, Kab. - 6204", "");
		dati2Map.put("Sarmi, Kab. - 8217", "KAB. SARMI");
		dati2Map.put("Sarolangun, Kab. - 3104", "KAB. SAROLANGUN");
		dati2Map.put("Sawahlunto, Kota. - 3493", "KOTA SAWAHLUNTO");
		dati2Map.put("Sekadau, Kab. - 5309", "KAB. SEKADAU");
		dati2Map.put("Seluma, Kab - 2307", "KAB. SELUMA");
		dati2Map.put("Seram Bagian Barat, Kota. - 8105", "");
		dati2Map.put("Seram Bagian Timur, Kota. - 8106", "");
		dati2Map.put("Seruyan, Kab. - 5810", "KAB. SERUYAN");
		dati2Map.put("Sibolga, Kota. - 3395", "KOTA SIBOLGA");
		dati2Map.put("Sidenreng Rappang, Kab. - 6117", "KAB. SIDENRENG RAPPANG");
		dati2Map.put("Sigi, Kab - 6010", "KAB. SIGI");
		dati2Map.put("Sijunjung, Kab - 3408", "KAB. SIJUNJUNG");
		dati2Map.put("Sikka, Kab. - 7407", "KAB. SIKKA");
		dati2Map.put("Simalungun, Kab. - 3304", "KAB. SIMALUNGUN");
		dati2Map.put("Simeuleu, Kab - 3216", "");
		dati2Map.put("Sinjai, Kab. - 6110", "KAB. SINJAI");
		dati2Map.put("Sintang, Kab. - 5305", "KAB. SINTANG");
		dati2Map.put("Situbondo, Kab. - 1230", "KAB. SITUBONDO");
		dati2Map.put("Solok Selatan, Kab. - 3404", "KAB. SOLOK SELATAN");
		dati2Map.put("Solok, Kab - 3412", "KAB. SOLOK");
		dati2Map.put("Solok, Kota. - 3495", "KOTA SOLOK");
		dati2Map.put("Soppeng, Kab (d/h Watansoppeng) - 6119", "KAB. SOPPENG");
		dati2Map.put("Sorong selatan, Kab. - 8404", "KAB. SORONG SELATAN");
		dati2Map.put("Sorong, Kab. - 8401", "KAB. SORONG");
		dati2Map.put("Sorong, Kota. - 8491", "KOTA SORONG");
		dati2Map.put("Sragen, Kab. - 0925", "KAB. SRAGEN");
		dati2Map.put("Subulussalam - 3219", "KOTA SUBULUSSALAM");
		dati2Map.put("Sukabumi, Kab. - 0109", "KAB. SUKABUMI");
		dati2Map.put("Sukabumi, Kota. - 0193", "KOTA SUKABUMI");
		dati2Map.put("Sukamara, Kab. - 5812", "KAB. SUKAMARA");
		dati2Map.put("Sumba Barat Daya, Kab. - 7417", "KAB. SUMBA BARAT DAYA");
		dati2Map.put("Sumba Barat, Kab. - 7412", "KAB. SUMBA BARAT");
		dati2Map.put("Sumba Tengah, Kab. - 7416", "KAB. SUMBA TENGAH");
		dati2Map.put("Sumba Timur, Kab. - 7411", "KAB. SUMBA TIMUR");
		dati2Map.put("Sumbawa Barat, Kab. - 7107", "KAB. SUMBAWA BARAT");
		dati2Map.put("Sumedang, Kab. - 0112", "KAB. SUMEDANG");
		dati2Map.put("Sumenep, Kab. - 1207", "KAB. SUMENEP");
		dati2Map.put("Supiori,Kab. - 8231", "KAB. SUPIORI");
		dati2Map.put("Tana Tidung, Kab. - 5412", "KAB. TANA TIDUNG");
		dati2Map.put("Tana Toraja, Kab. - 6106", "KAB. TANA TORAJA");
		dati2Map.put("Tanah Bumbu, Kab. - 5110", "KAB. TANAH BUMBU");
		dati2Map.put("Tanah Datar, Kab. - 3407", "KAB. TANAH DATAR");
		dati2Map.put("Tanah Laut, Kab. - 5102", "KAB. TANAH LAUT");
		dati2Map.put("Tanggamus, Kab. - 3906", "KAB. TANGGAMUS");
		dati2Map.put("Tanjung Balai, Kota. - 3394", "KOTA TANJUNG BALAI");
		dati2Map.put("Tanjung Jabung Barat, Kab. - 3107", "KAB. TANJUNG JABUNG BARAT");
		dati2Map.put("Tanjung Jabung Timur, Kab. - 3108", "KAB. TANJUNG JABUNG TIMUR");
		dati2Map.put("Tapanuli Selatan, Kab. - 3310", "KAB. TAPANULI SELATAN");
		dati2Map.put("Tapanuli Tengah, Kab. - 3309", "KAB. TAPANULI TENGAH");
		dati2Map.put("Tapanuli Utara, Kab. - 3308", "KAB. TAPANULI UTARA");
		dati2Map.put("Tapin, Kab. - 5103", "KAB. TAPIN");
		dati2Map.put("Tasikmalaya, Kab. - 0113", "KAB. TASIKMALAYA");
		dati2Map.put("Tebing Tinggi, Kota. - 3391", "KOTA TEBING TINGGI");
		dati2Map.put("Tebo, Kab. - 3109", "KAB. TEBO");
		dati2Map.put("Teluk Bintuni, Kab. - 8407", "KAB. TELUK BINTUNI");
		dati2Map.put("Teluk Wondama, Kab. - 8408", "KAB. TELUK WONDAMA");
		dati2Map.put("Tembrauw, Kab - 8409", "");
		dati2Map.put("Ternate, Kota. - 8390", "KOTA TERNATE");
		dati2Map.put("Tidore Kepulauan, Kota. - 8391", "KOTA TIDORE KEPULAUAN");
		dati2Map.put("Timor-Tengah Selatan, Kab. - 7402", "KAB. TIMOR TENGAH SELATAN");
		dati2Map.put("Timor-Tengah Utara, Kab. - 7403", "KAB. TIMOR TENGAH UTARA");
		dati2Map.put("Toba Samosir, Kab. - 3313", "KAB. TOBA SAMOSIR");
		dati2Map.put("Tojo Una-Una, Kab. - 6008", "KAB. TOJO UNA-UNA");
		dati2Map.put("Tolikara, Kab. - 8223", "KAB. TOLIKARA");
		dati2Map.put("Toli-Toli, Kab. - 6004", "KAB. TOLITOLI");
		dati2Map.put("Toraja Utara, Kab - 6125", "KAB. TORAJA UTARA");
		dati2Map.put("Trenggalek, Kab. - 1220", "KAB. TRENGGALEK");
		dati2Map.put("Tual, Kota. - 8192", "KOTA TUAL");
		dati2Map.put("Tuban, Kab. - 1228", "KAB. TUBAN");
		dati2Map.put("Tulang Bawang Barat, Kab - 3911", "KAB. TULANG BAWANG BARAT");
		dati2Map.put("Wajo, Kab. - 6103", "KAB. WAJO");
		dati2Map.put("Wakatobi, Kab. - 6905", "KAB. WAKATOBI");
		dati2Map.put("Waropen, Kab. - 8224", "KAB. WAROPEN");
		dati2Map.put("Way Kanan, Kab. - 3908", "KAB. WAY KANAN");
		dati2Map.put("Wonosobo, Kab. - 0920", "KAB. WONOSOBO");
		dati2Map.put("Yahukimo, Kab. - 8222", "KAB. YAHUKIMO");
		dati2Map.put("Yalimo, Kab. - 8237", "KAB. YALIMO");
	}
	
	public static DataMapping get() {
		if (dataMapping == null) dataMapping = new DataMapping();
		return dataMapping;
	}
	
	public String getDati2Mapping(String dati2) {
		return dati2Map.get(dati2);
	}
}