package com.btpn.migration.los.constant;

import java.util.ArrayList;
import java.util.List;

public class IgnoreFile {
	
	private static String[] unOpenedFile = new String[] {
			"._001. Henywati - 2018.xls",
			"._006. Ison Ginting - 2018.xls",
			"079. Ng Gim An\079. Ng Gim An - Perpanjangan & Tambahan.xlsx",
			"102. Deliana.xlsx",
			"112. Eddy - Banding.xlsx",
			"112. Eddy.xlsx",
			"155.I. CV Semangat Jaya.xlsx",
			"155.II. CV Semangat Jaya.xlsx",
			"155.III. CV Semangat Jaya.xlsx",
			"222. Umar.xlsx",
			"247. CV. Sentosa Jaya Abadi.xlsx",
			"254.I Nuromlah - Penarikan Jaminan & Pelunasan Sebagian.xlsx",
			"100. Hersen - Seasonal Limit.xlsx",
			"148. Eisen Gauw.xlsx",
			"226. Drs. Budiman.xlsx",
			"079. Ng Gim An - Perpanjangan & Tambahan.xlsx"
	};
	
	private static String[] unStandardFile = new String[] {
		"264. Aarti Jaya Group.xls"	
	};
	
	private static String[] ignoredFile = new String[] {
			"054. CV. Megah Surya Abadi - 2018 (RAC ABF).xlsx",
			"RAC ABF rev 1.xlsx",
			"067. Hok Kie - Reinstate.xlsx",
			"085. PT. Neoplast Packaging - PAB Reinstate.xlsx",
			"209. Ruddy Sutedja - RAC ABF.xls",
			"015. PT Teknik Jaya Abadi - Banding - RAC ABF.xls",
			"065. Muhammad Syafei - Seasonal Limit.xlsx",
			"155.III. CV Semangat Jaya - CPLTD & Bunga.xls",
			"001. Rino Limbara - Memo Review.xlsx",
			"Memo Review Nan Riang.xlsx",
			"RAC ABF 2017 Nan Riang Revisi.xlsx",
			"020. PT. Sinar Sakti Indonesia.xlsx",
			"029. PT. Abadi Sarana Transport - Banding (RAC ABF).xlsx",
			"029. PT. Abadi Sarana Transport - RAC ABF.xlsx",
			"Foto PT CUAN.xlsx",
			"mutasi rekening bni.xls",
			"mutasi rekening panin.xls",
			"mutasi rekening pribadi.xls",
			"mutasi rekening pt cuan.xls",
			"neraca 2017.xls",
			"perhitungan dsr.xls",
			"041. PT. Sinar Sakti Indonesia - GP ke 3.xlsx",
			"043. Safran Herianto - Memo Review.xlsx",
			"053. CV Berkat - GP.xlsx",
			"067. Halimah - Seasonal Limit.xlsx",
			"072. PT Rimba Prajna Mulia - RAC ABF.xlsx",
			"099. PT. BPR Utomo Manunggal Sejahtera -CPLTD.xls",
			"101.I. CV Tiga Pilar Transindo - RAC ABF.xlsx",
			"146. CV Berkat.xlsx",
			"155. PT. Tambang Bukit Tambi - RAC ABF.xlsx",
			"160. PT Tabara Neddy Energi - RAC ABF.xlsx",
			"Template Slik checking CBAS.XLSX",
			"Template Slik checking CBAS.XLSX",
			"11. Template Pengajuan Penilaian Jaminan oleh Internal Appraiser_(2018).xls, not a migr",
			"triger an.Hendra Ali.xlsx",
			"178. PT Taruna Jaya Sempurna - RAC ABF.xls",
			"186. PT. Alisan Catur Adhirajasa - CPLTD.xls",
			"187. CV Sumatera Nusantara Abadi - RAC ABF.xlsx",
			"189. CV. Sumber Berkat Abadi - RAC ABF.xlsx",
			"192. PT. Sinar Sakti Indonesia - GP ke 4.xlsx",
			"198. PT. Buana Pusat Mulia - RAC ABF.xlsx",
			"204. PT. Musi Nauli Lestari.xls",
			"219. PT Prima Dito Nusantara - RAC ABF.xlsx",
			"038. CV Panyileukan - Reinstate.xlsx",
			"040. Charles Charlie Pranolo - Reinstate.xlsx",
			"040.I. Charles Charlie Pranolo - Reinstate.xlsx",
			"Ilustrasi jadwal angsuran.xlsx",
			"Ilustrasi Angsuran Debitur.xlsx",
			"141. Wendy Christian Setiawan - Reinstate.xlsx",
			"DSR ACM BUDI SANTOSO, THEN add&renewal 20032018.xls",
			"FOTO USAHA BUDI SANTOSO, THEN(GUDANG)1.xlsx",
			"FOTO USAHA BUDI SANTOSO, THEN(GUDANG)2.xlsx",
			"QCACS Review - Budi Santoso, Then.xls",
			"DSR ACM_PT MURBA JAYA ABADI 09042018.xls",
			"Foto Usaha PT MURBA JAYA ABADI 2018.xlsx",
			"102. PT Sinar Utama Sejahtera - Seasonal Limit.xls",
			"QCACS Review - Elkana Setiawan Barus.xls",
			"SIMULASI DSR.xls",
			"189. Lanny Inggriani - Foto Usaha.xlsx",
			"QCACS Review - Sugianto, Ir.xls",
			"SIMULASI DSR Sugianto 2018.xls",
			"210. Herry Sanjaya - QCACS Review.xls",
			"213. PT Anugrah Mega Gemilang - QCA.xls",
			"DSR_ACM_PT Anugrah Mega Gemilang.xls",
			"aDSR_ACM_LUCIA ROSARYLANYGROUP_24092018.xls",
			"QCACS Review - Cv Indo Bali Jaya.xls",
			"QCACS Review - Cv Matahari Bali Sejahtera.xls",
			"QCACS Review - Cv Rosa Raharja.xls",
			"QCACS Review - Lucia Rosarylany Prabawa.xls",
			"242. CV Bhumi Cipta Mandiri  - CPLTD Okt 2018.xls",
			"foto usaha CV Bhumi Cipta mandiri.xlsx",
			"LIP PB.xls",
			"LIP PELUNASAN.xls",
			"LIP PRK.xls",
			"QCACS Review - Cv Bhumi Cipta Mandiri.xls",
			"Anton Hariyanto - CPLTD.xls",
			"QCACS Review - Anton Hariyanto.xls",
			"251. PT. Surya Karya Setiabudi - RAC ABF.xlsx",
			"264. PT Kinarya Tunas Artha - CPLTD.xlsx",
			"061. PT Kayana Indonesia - RAC ABF.xlsx",
			"091. Bambang Solikin - Seasonal Limit.xlsx",
			"093. CV. Gasper - Seasonal Limit.xlsx",
			"200. PT. Kharisma Kencana Nusantara - RAC ABF.xlsx",
			"215. PT. Mandalaputra Prima Mandiri - RAC ABF.xlsx",
			"237. Bambang Solikin - Seasonal Limit.xlsx",
			"238. PT Diantrijaya Utama Mukti - CSC Supply Chain.xls",
			"006. PT. Gatra Kaltim Jaya - Data Pendukung.xls",
			"006. PT. Gatra Kaltim Jaya - RAC ABF.xlsx",
			"009. PT. Intika Delta Borneo - RAC ABF.xlsx",
			"011. PT. Pelayaran Intan - RAC ABF.xlsx",
			"016. PT. WINGS Sejati - Perhitungan DSR.xls",
			"016. PT. WINGS Sejati - RAC ABF.xlsx",
			"020. PT. Danny Samudera Raya Line - Aktivitas Rekening.xls",
			"020. PT. Danny Samudera Raya Line - Perhitungan DSR.xls",
			"020. PT. Danny Samudera Raya Line - RAC ABF.xlsx",
			"035. PT. Lubrisindo Jaya Gemilang - RAC ABF Regularisasi 2.xlsx",
			"035. PT. Lubrisindo Jaya Gemilang - RAC ABF.xlsx",
			"035. PT. Lubrisindo Jaya Gemilang - Regularisasi 2 (RAC ABF).xlsx",
			"035.I. PT. Lubrisindo Jaya Gemilang - RAC ABF.xlsx",
			"035.III. PT. Lubrisindo Jaya Gemilang - RAC ABF.xlsx",
			"040. PT. Dharma Permai - RAC.xlsx",
			"041. Usman - RAC ABF.xlsx",
			"049. RAC_PT. Berkat Anugerah Sejahtera.xlsx",
			"049.I. PT. Berkat Anugerah Sejahtera - RAC.xlsx",
			"049.II. PT. Berkat Anugerah Sejahtera - RAC.xlsx",
			"053. RAC_CV. Paris Indo Lisensi.xlsx",
			"054. CV. Mega Jasa - DSR.xls",
			"059. PT. Samudra Jaya Perkasa - RAC ABF 2018.xlsx",
			"059. PT. Samudra Maju Perkasa - RAC ABF 2018 Regulasi.xlsx",
			"059. PT. Samudra Maju Perkasa - Regularisasi 2 (RAC ABF).xlsx",
			"061. PT Rante Mutiara Insani - RAC ABF.xlsx",
			"061.I. PT. Rante Mutiara Insani - RAC ABF.xlsx",
			"065. Hendrik Fernandez - Perhitungan DSR.xlsx",
			"067. PT. Artha Samudra Kaltim - RAC ABF.xlsx",
			"077. CV Sentosa Indah Perkasa - RAC ABF.xlsx",
			"078. PT. MASADA JAYA LINE - RAC ABF.xlsx",
			"079. PT. Capricorn Group - DSR.xlsx",
			"084. PT. Usaha Gas Elpindo - Perhitungan DSR.xlsx",
			"097. PT. Karya Prima Mandiri Pratama - RAC ABF.xlsx",
			"097.I. PT. Karya Prima Mandiri Pratama - RAC ABF.xlsx",
			"100. RAC ABF PT. Wings Sejati.xlsx",
			"101. CV Anugerah Jaya Abadi Rental - RAC ABF.xlsx",
			"101.II. CV Anugerah  Jaya Abadi Rental - RAC ABF.xlsx",
			"104. PT. Pelayaran Tonicogita Ekamarindo -RAC ABF.xlsx",
			"104.I. PT. Pelayaran Tonicogita Ekamarindo - Regularisasi ABF.xlsx, not a migration fil",
			"106. PT. Gatra Kaltim Jaya - RAC ABF.xlsx",
			"106.I. PT Gatra Kaltim Jaya - Regularisasi (RAC ABF).xlsx",
			"106.III. PT Gatra Kaltim Jaya - RAC ABF.xlsx",
			"106.ll. PT Gatra Kaltim Jaya -RAC ABF.xlsx",
			"111. PT. Cakrawala Putra Bersama - RAC ABF.xlsx",
			"113. PT. Bintang Nusantara Linda - DSR.xls",
			"113. PT. Bintang Nusantara Linda - RAC ABF.xlsx",
			"113.I. PT. Bintang Nusantara Linda - RAC ABF.xlsx",
			"114. CV. Mega Jasa - RAC ABF.xlsx",
			"114.I. CV. Mega Jasa - RAC ABF.xlsx",
			"115. PT. Andalan Lancar Niaga - RAC ABF.xlsx",
			"115. RAC ABF 2017 - PT Andalan Lancar Niaga - Regularisasi 2.xlsx",
			"115.I. PT. Andalan Lancar Niaga - RAC ABF.xlsx",
			"115.II. PT. Andalan Lancar Niaga - RAC ABF.xlsx",
			"Data pendukung PT. Andalan Lancar Niaga.xls",
			"Data pendukung PT. Karya Bukit Mandiri.xls",
			"Perhitungan DSR Master BP Mix 2018.xls",
			"012. Hengky Onggie - PAB Reinstate.xlsx",
			"028. PT Trimitra Maju Persada (RAC ABF).xlsx",
			"104. PT. Indo Timur Prima - PAB Reinstate.xlsx",
			"Ilustrasi - Ferdinand Rianto.xlsx",
			"122. Filasri - Tambahan (PAB Reinstate).xlsx",
			"140. Ng Swi Piu - List Track Recor Pembayaran Angsuran.xls",
			"140. Ng Swi Piu - Simulasi DSR.xlsx",
			"145. Hengky Onggie - PAB Reinstate.xlsx",
			"159. Rudy Herman Ishak - Tambahan (PAB Reinstate).xlsx",
			"175.I PT. Eboni Bintang Rejeki - Banding (Simulasi DSR).xls",
			"199. PT. Nenggapratama Internusantara - Tambahan.xls",
			"202. PT. Jaya Mega Mandiri Bangunan - Tambahan (RAC ABF).xlsx",
			"Copy of Simulasi DSR versi RCR.xls",
			"Copy of Simulasi DSR.xls",
			"006. Ison Ginting - RAC ABF.xlsx",
			"015. PT Teknik Jaya Abadi - Tambahan - RAC ABF.xlsx",
			"056. PT. Angelia Putri Pratama - RAC ABF.xlsx",
			"064. PT. Angelia Putri Pratama - RAC ABF.xlsx",
			"076. Hary Cahyadi - Seasonal Limit.xlsx",
			"Laporan Kunjungan Usaha.xlsx",
			"216. PT Usaha Remaja Mandiri - RAC ABF.xlsx",
			"214. PT. Wira Karya Makmur - RAC ABF.xlsx",
			"206.IV PT Lematang - RAC ABF.xlsx",
			"206.III. PT Lematang - RAC ABF.xlsx",
			"206.II. PT Lematang - RAC ABF.xlsx",
			"206.I. PT Lematang - RAC ABF.xlsx",
			"206. PT Lematang - RAC ABF.xlsx",
			"177.I. Muksin - RAC ABF.xlsx",
			"177. Muksin - RAC ABF.xlsx",
			"169. PT Bintang Beton Mandala - RAC ABF.xlsx",
			"152.II. CV Maju Jaya Transport - RAC ABF.xlsx",
			"152.I. CV Maju Jaya Transport - ABF.xlsx",
			"152. CV Maju Jaya Transport - RAC ABF.xlsx",
			"143. PT. MPX Logistic International - RAC ABF.xlsx",
			"115. CV. Sukses Makmur Abadi - RAC ABF.xlsx",
			"110. CV Putra Kusuma - RAC ABF.xlsx",
			"102. Acing Harto - RAC ABF.xlsx",
			"101.II. CV Tiga Pilar Transindo - RAC ABF.xlsx",
			"101. CV Tiga Pilar Transindo - RAC ABF.xlsx",
			"046. David Ju - RAC ABF.xlsx",
			"045. PT Bintang Selatan Agung - RAC ABF.xlsx",
			"017. CV. Maju Jaya Transport - RAC ABF.xlsx",
			"262. PT. Huthama Cahaya Langgeng - RAC ABF.xlsx",
			"245. Syafri Tanjung.xlsx",
			"199. PT Cipta Samudera Mandiri - RAC ABF.xlsx",
			"172. PT Citra Andalas Mandiri - Tambahan - RAC ABF.xlsx",
			"157. PT Angelia Putri Pratama - Tambahan (RAC ABF).xlsx",
			"154. PT SAS Bangun Alam Perkasa -RAC ABF.xlsx",
			"104.I. PT. Pelayaran Tonicogita Ekamarindo - Regularisasi ABF.xlsx",
			"11. Template Pengajuan Penilaian Jaminan oleh Internal Appraiser_(2018).xls",
			"202.I. PT. Jaya Mega Mandiri Bangunan - RAC ABF (Ganti Alat).xlsx"
	};
	
	private static List<String> ignoredlist = new ArrayList<String>();
	public static boolean isIgnore(String filename) {
		if (ignoredlist.isEmpty()) {
			for (String f : ignoredFile) { ignoredlist.add(f); }
			for (String f : unOpenedFile) { ignoredlist.add(f); }
			for (String f : unStandardFile) { ignoredlist.add(f); }
			
		}
		
		return ignoredlist.contains(filename);
	}
}
