insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0006', 'LAMPUNG WOLTER M 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0006', 'LAMPUNG WOLTER M 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0008', 'BANJARMASIN A. YANI', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0012', 'BOGOR PADJAJARAN', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0015', 'CIREBON WAHIDIN', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0016', 'MALANG SUTOYO', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0018', 'SEMARANG MT HARYONO 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0018', 'SEMARANG MT HARYONO 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0019', 'YOGYAKARTA BINTARAN 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0019', 'YOGYAKARTA BINTARAN 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0020', 'SURAKARTA SLAMET RIYADI', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0021', 'MADIUN SALAK', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0025', 'SURABAYA INDRAPURA', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0026', 'MEDAN PUTRI HIJAU 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0026', 'MEDAN PUTRI HIJAU 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0027', 'KUDUS SUDIRMAN', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0029', 'MAKASSAR BAWAKARAENG', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0031', 'PALEMBANG SUDIRMAN', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0032', 'MANADO SAM RATULANGI', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0034', 'KEDIRI KATAMSO', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0035', 'PURWOKERTO PASAR WAGE', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0039', 'SURABAYA KERTAJAYA', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0043', 'SME - SUPPLY CHAIN', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0043', 'SME - BTB', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0059', 'BANDUNG BURANGRANG', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0227', 'PEMATANG SIANTAR SUTOMO', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0312', 'PALEMBANG CINDE 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0312', 'PALEMBANG CINDE 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0394', 'BALIKPAPAN SUDIRMAN', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0396', 'JAKARTA PANGLIMA POLIM', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0449', 'JAKARTA KELAPA GADING', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0451', 'JAKARTA PLUIT', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0457', 'JAKARTA SUNTER', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0459', 'JAKARTA MANGGA DUA', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0460', 'SURABAYA DARMO GOLF 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0460', 'SURABAYA DARMO GOLF 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0461', 'TANGERANG BSD', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0470', 'PALU MASOMBA', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0478', 'PEKANBARU RIAU 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0478', 'PEKANBARU RIAU 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0479', 'MEDAN ASIA', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0485', 'DENPASAR TEUKU UMAR', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0488', 'JAKARTA TAMAN PALEM 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0488', 'JAKARTA TAMAN PALEM 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0490', 'JAKARTA TANAH ABANG', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0507', 'MEDAN GOLDEN TRADE CENTRE', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0510', 'JAKARTA PECENONGAN 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0510', 'JAKARTA PECENONGAN 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0514', 'JAKARTA KEBON JERUK INTERCON', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0524', 'TANGERANG GADING SERPONG', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0532', 'SURABAYA JEMUR ANDAYANI', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0541', 'MAKASSAR PANAKUKANG', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0547', 'BANDUNG KOPO 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0547', 'BANDUNG KOPO 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0549', 'SURABAYA KEDUNGDORO', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0551', 'MEDAN CIREBON 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0551', 'MEDAN CIREBON 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0554', 'BEKASI MAS 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0554', 'BEKASI MAS 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0557', 'JAKARTA JATINEGARA 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0557', 'JAKARTA JATINEGARA 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0562', 'MAKASSAR ALAUDDIN', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0563', 'MATARAM PEJANGGIK', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0566', 'TASIKMALAYA YUDANEGARA', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('7107', 'PONTIANAK A. YANI', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('7108', 'KENDARI MADONGA', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('7211', 'SAMARINDA PAHLAWAN 2', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('7211', 'SAMARINDA PAHLAWAN 1', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('7353', 'JAMBI TALANG BANJAR', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('7547', 'AMBON A.Y. PATTY', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('B105', 'SAM REGION 5', 1, 1, 1, 1);
insert into dlos_branch(branchCode, branchName, `LOBId`, `areaId`,`isActive`, appIdSequence) values('0449', 'COM KCP MENARA BTPN', 1, 1, 1, 1);
