
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8103', 'REGION 3 - SUMBAGSEL', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8103', 'REGION 3 - SUMBAGSEL', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8107', 'REGION 7 - KALIMANTAN', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8104', 'REGION 4 - JAWA BARAT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8105', 'REGION 5 - JATENG DIY', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8105', 'REGION 5 - JATENG DIY', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8105', 'REGION 5 - JATENG DIY', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8105', 'REGION 5 - JATENG DIY', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8105', 'REGION 5 - JATENG DIY', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8105', 'REGION 5 - JATENG DIY', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8108', 'REGION 8 - IBT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8103', 'REGION 3 - SUMBAGSEL', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8108', 'REGION 8 - IBT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8105', 'REGION 5 - JATENG DIY', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8188', 'SC HO', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8199', 'MASS ACQUISITION', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8104', 'REGION 4 - JAWA BARAT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8103', 'REGION 3 - SUMBAGSEL', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8103', 'REGION 3 - SUMBAGSEL', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8107', 'REGION 7 - KALIMANTAN', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8108', 'REGION 8 - IBT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8121', 'REGION 1B - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8108', 'REGION 8 - IBT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8104', 'REGION 4 - JAWA BARAT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8104', 'REGION 4 - JAWA BARAT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8102', 'REGION 2 - SUMBAGUT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8111', 'REGION 1A - JAKARTA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8108', 'REGION 8 - IBT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8106', 'REGION 6 - JATIM, BALI, NUSRA', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8104', 'REGION 4 - JAWA BARAT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8107', 'REGION 7 - KALIMANTAN', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8108', 'REGION 8 - IBT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8107', 'REGION 7 - KALIMANTAN', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8107', 'REGION 7 - KALIMANTAN', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8103', 'REGION 3 - SUMBAGSEL', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('8108', 'REGION 8 - IBT', 1, 1);
insert into dlos_region(regionCode, regionName, `LOBId`, `isActive`) values('#N/A', 'HO - COMERCIAL', 1, 1);